- src/handlers/update-user.ts
- src/helpers/generate-auth-response.ts
- src/models/User.ts
- src/routes/tsoa/login.ts
- src/routes/tsoa/users.ts
- src/templates/render.ts
- src/types/Profile.ts
- src/types/index.ts
- test/models/User.spec.ts
- test/routes/tsoa/authenticate.spec.ts
This fixes some issues with updates to the profile not making it to the sql database. It's a bit nasty now with the durable objects being snake cased so it matches the oauth2-standard, but the sql entities being camel cased which feels more javascript. And then they are once again actually snake cased in the database :)
> fix: use snake cased entities in durable objects

- src/routes/tsoa/applications.ts
- src/routes/tsoa/connections.ts
Not really sure why we get an array back for the update.. I'm guessing we could take the first result and just cast it to number for now?
> fix: cast bigint to number

- src/routes/tsoa/applications.ts
It wasn't possible to provide the id when creating the application before which was unpractical.. Now it's optional. Also fixed so the tenantId isn't required as it's passed in the url.
> Application id

- src/errors.ts
- src/routes/tsoa/login.ts
- src/templates/reset-password.liquid
I saw this in a previous PR. Prettier must have done this
Currently emails are busted like this
> fix: password reset emails

- src/controllers/email.ts
- src/models/User.ts
- src/routes/tsoa/login.ts
- test/models/User.spec.ts
Started cleaning up how the email validation works:
- Send a mail with a code when a user signs up. This can be used to validate the email later
- Moved the mail templates to a separate file
- Changed so that the email validation flag is stored as part of the profile
- Fixed so that the connection is added to the profile when a new passord is registered
- Refactored some tRPC endpoints so they take the email and tenantId as well (as this is needed to update the profile)
> fix: refactor signup flow

- package.json
- src/models/User.ts
- src/routes/tsoa/users.ts
- src/types/Profile.ts
- test/models/User.spec.ts
This is freakin cool. Zod finally solves the issue with unsafe types runtime without adding more cruft to the code.
As the durable object storage just handles strings I would really like to have a safe way of getting and storing data there. This is a first POC and the next step would be make a generic wrapper for the storage.
> fix: added zod for type safe parsing

- scripts/init-production.sh
- scripts/init.sh
- src/migrate/migrations/2023-08-15T09:17:35_domains.ts
- src/migrate/migrations/index.ts
- src/routes/swagger-ui.ts
- src/routes/tsoa/domains.ts
- src/types/Domain.ts
- src/types/Env.ts
- src/types/sql/Domain.ts
- src/types/sql/db.ts
- src/types/sql/index.ts
- wrangler.toml
Ok, got 2 things in here.. The main thing is adding the basic sql models to handle domains. Currently it's just the sql stuff so we know which tenant has which custom domains connected to it. The next step is to integrate with the cloudflare api so we can manage the custom domains there.
I also did some prepping to make it possible to deploy this to prod. I added a small script to create the infra needed and added the config variables to the toml file.
> feat: added sql support for domains

- src/hooks/update-client.ts
- src/models/DefaultSettings.ts
- src/services/clients.ts
- src/types/Client.ts
- src/types/Env.ts
- src/types/sql/Connection.ts
- test/fixtures/context.ts
- test/routes/tsoa/token.spec.ts
- test/services/getClient.spec.ts
This got a bit more messy than I thought.
The idea is that we can store default settings in a env-variable and it will decorate the clients stored in KV-storage in run time. There's a few benefits with this:
- You don't have to type so much.. Just add a empty google-connection and it will use the defaults
- We don't have to persist sensitive data somewhere it can be accessed. The environment variables can be encrypted so there will be no easy way to get hold of private keys and such.
> feat: make it possible to store default settings in a env variable

- src/models/User.ts
- src/server.ts
- src/services/events.ts
- wrangler.toml
If the queue isn't defined in the toml-file it will call the updateUser directly instead. This way we can run the project remotely which will make the DX much better.
> fix: skip queues if not defined

- .husky/pre-commit
- package.json
- yarn.lock
we're doing this on Insights & Commerce
I'd rather not use pre-commit hooks but the VS Code Prettier plugin is not fit for purpose :clown_face: :clown_face: :clown_face: 
I'd rather disable it and add this to each repo
> feat: run prettier precommit with husky

- src/migrate/migrations/2023-08-22T15:06:26_dkim.ts
- src/migrate/migrations/2023-08-31T13:50:12_mailgun.ts
So, it seem the kysely handles the casing in the migration.. Tried to run the latest migration and got this error:
"message": "target: auth2-dev.-.primary: vttablet: rpc error: code = FailedPrecondition desc = Can't DROP 'dkim_private_key'; check that column/key exists (errno 1091) (sqlstate 42000) (CallerID: 4vcjzvar8vbfzhh2ted8): Sql: \"alter table domains add column email_service varchar(255), add column email_api_key varchar(255), add column dkim_private_key varchar(2048), add column dkim_public_key varchar(2048), drop column dkim_private_key, drop column dkim_private_key\", BindVars: {REDACTED}"
> fix: remove dkim migration

- src/email-templates/code.mjml
- src/email-templates/verify-email.mjml
- src/templates/email/code.liquid
- src/templates/email/verify-email.liquid
Ooops! I didn't actually use the logo in the template
I can manually test this by pushing up the templates... no luck!
*This PR does the correct task of using the `logo` variable*
I'm trying this with Breakit but it's falling back to the Sesamy logo
> feat: actually use the logo in the mjml template

- test/fixtures/context.ts
- test/routes/tsoa/passwordless.spec.ts
This tests and asserts existing functionality and shows that we're applying the correct client logo *EXCEPT* of course in reality this isn't happening :smile: 
*why?* because the logo is inside the `tenant` key of the `client`, not at the top level! :smile: 
_what I will do_ is fix these types on the next PR, and then the tests, and then it should _just_ work :smile:
> feat: fix use client logo on email

- src/types/Token.ts
this fixes the types used for TSOA :smile: 
*BUT* it still doesn't work of course, we'll just get a meaningful error back :sunglasses:
> fix: audience is sent as part of client credential

- src/routes/tsoa/users-mgmt.ts
See linked ticket! :smile: 
This is currently pushed up to dev e.g. https://auth2.sesamy.dev/api/v2/users/55yGva-RrwP4GdlhExiDQ
@markusahlstrand you can see this working here https://github.com/sesamyab/auth0-management-api-demo/blob/master/run-auth2.mjs
pull the repo down. it's just ES modules :smile:   I just type `node run-auth2.mjs` into my console :exploding_head: 
how cool is that
> feat: clone existing user route but for api/v2

- src/constants.ts
- src/routes/tsoa/users-mgmt.ts
As discussed, this seems like the best way to support having multiple tenants under one Auth domain
> feat: require tenant-id header in management API routes

- src/routes/tsoa/users-mgmt.ts
As discussed, for now all the new management API routes can appear under the same label on the docs
> feat: tag route as management-api

- src/middlewares/cors.ts
- src/models/User.ts
- src/routes/tsoa/users-mgmt.ts
- src/types/sql/User.ts
Quite a few changes are needed if we're going to use the management API endpoints to control the users in auth-admin
*BUT* The existing user pages do not work, so I suppose we need some way to edit users, and this isn't time wasted :thinking:
> feat: react-admin read user management API endpoints

- src/errors.ts
- src/hooks/migrate-password.ts
- src/models/User.ts
- src/routes/tsoa/users-mgmt.ts
- test/fixtures/do-storage.ts
- test/models/User.spec.ts
Added a function that adds a linked user as a connection, which is the first step of linking users. This way a user that has a linked user show up with the linked-user tag in the auth-admin.
It does not yet store information in the linked user so it won't change the login flow yet.
When writing the test I realized that we should have a fixture for the storage so I added that and refactored the other model tests.
> feat: add linked user connection

- src/models/DefaultSettings.ts
- src/services/clients.ts
We didn't pick up the default allowed urls from the env variable.
> fix: add defaults for allowed urls

- src/authentication.ts
- src/routes/tsoa/users-mgmt.ts
As we don't pass the tenenat-id in the params for the users endpoint we need to check the header as well.
> fix: check permissions based on tenant id header

- src/helpers/account-linking.ts
- src/models/User.ts
- src/routes/tsoa/authenticate.ts
- test/models/User.spec.ts
Patched the code flow so it uses handles linked users. It's a bit tricky as we're actually fetching the user and store it in a the state, so there's not a single point where we can handle the linked accounts. Maybe it would be better to keep the state leaner and try to have one point where we fetch the profiles.
> feat: tested to detect linked accounts for code

- src/types/Token.ts
The auth0 library doesn't pass a scope to the client credentials endpoint.
> fix: make scope optional for client credintials

- src/controllers/email.ts
- src/email-templates/code.mjml
- src/templates/email/code.liquid
- src/types/Client.ts
- test/fixtures/context.ts
- test/services/getClient.spec.ts
On this PR
* support URL is *not* required in nested `tenant` object in `client`
* if does not exist fallback to our default - https://support.sesamy.com
:question: _anything else needed for CRUD_ :question: 
Check all types could have `support_url`
> feat: support_url fixes tenant CRUD

- src/controllers/email.ts
- src/locales/sv.ts
- src/routes/tsoa/passwordless.ts
- test/routes/tsoa/passwordless.spec.ts
I tested this on the Commerce deploy and we stay on Swedish -> https://commerce-ds2s9rn6m.vercel.sesamy.dev/
*BUT* I noticed that the `redirecting` page keeps ending up back on English. I can look at that also
> feat: expired link redirect needs i18n

- scripts/create-mjml-templates.sh
- src/controllers/email.ts
- src/email-templates/code.mjml
- src/email-templates/link.mjml
- src/routes/tsoa/passwordless.ts
- src/templates/email/link.liquid
- test/routes/tsoa/passwordless.spec.ts
I'll use the copy provided by @markusahlstrand from the nuked PR https://github.com/sesamyab/auth/pull/172 
---------------------------------------------------------------
@markusahlstrand this is actually quite duplicated. I could have another look tomorrow in how to get logic into the liquid templates, ideally we'd have something testing visually the output of the templates though. Otherwise I'd rather just duplicate and quickly QA both templates...
It could be that instead we extract out common parts into partials... TBD!
> feat: new template for code emails and send this depending on call to passwordless/start

- src/utils/validate-redirect-url.ts
- test/utils/validate-redirect-url.spec.ts
This _should_ fix everything we need for a release across all `client_id`s :crossed_fingers: 
_If we merge this then all the cron job tests should pass again_ :checkered_flag:
> feat: hardcoded list of allowed callback URL

- src/utils/validate-redirect-url.ts
*OR* @markusahlstrand , we just add these to the breakit clients on auth2 dev & prod
I'll be doing this on dev anyway for `breakit` but we have several client_ids, comments welcome!
> feat: new breakit logout user route needs adding to hardcoded allowed callback URLs

- src/adapters/planetscale/users/createUser.ts
- src/routes/management-api/users.ts
- src/types/auth0/UserResponse.ts
This is the response that we get back from the Auth0 mgmt API after creating a user
```
{
created_at: '2023-10-25T19:00:05.668Z',
email: 'new-test-user@hey.com',
email_verified: false,
identities: [
{
connection: 'Username-Password-Authentication',
user_id: '653965b5922a5416607b4b47',
provider: 'auth0',
isSocial: false
}
],
name: 'new-test-user@hey.com',
nickname: 'new-test-user',
picture: 'https://s.gravatar.com/avatar/e9b89abdaf7818d6dcb0bb3cda43c64a?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fne.png',
updated_at: '2023-10-25T19:00:05.668Z',
user_id: 'auth0|653965b5922a5416607b4b47',
user_metadata: {}
}
```
We also need the `user_id` in React Admin
> fix: mgmt API POST create user

- src/adapters/interfaces/User.ts
- src/adapters/planetscale/users/listUsers.ts
Ooops! No wonder pagination wasn't working
This is what Auth0 does, and this is what our Auth0DataAdaptor expects :muscle:
> fix: do not nest totals

- src/utils/validate-redirect-url.ts
- test/utils/validate-redirect-url.spec.ts
It seems the cloudflare indeed has issues with wildcards when creating URL's.
Changed the tests a bit so they are using validateUrl instead of validateRedirectUrl as it injecting a lot of deafults which makes the tests less reliable.
> fix: cloudflare and url wildcards

- .github/workflows/unit-tests.yml
- package.json
- src/adapters/in-memory/logs/list.ts
- src/adapters/in-memory/user/listUsers.ts
- src/adapters/planetscale/users/listUsers.ts
- src/migrate/index.ts
- src/routes/tsoa/applications.ts
- src/routes/tsoa/dbconnection.ts
- src/routes/tsoa/login.ts
- src/routes/tsoa/userinfo.ts
- tsconfig.json
- yarn.lock
Previously when I tried to run `tsc` it was flagging all kinds of files inside `node_modules`
This seems to be better now _although_ it's still looking inside the `build` folder :thinking: 
It also flags quite a few errors which seem legit!
* `/userinfo` endpoint - looks like has legit type issue. I could look into how this is queried... I'm guessing that the runtime is fine but the types aren't correct
* `/build/routes.ts` - as this is imported in `app.ts`, typescript is checking it.Why is this wrong though?
*because this guy's library is wrong!* :smile:   No fear though Markus I've made a PR -> https://github.com/markusahlstrand/tsoa-hono/pull/1  :heavy_check_mark:  *these fixes are working now*
> feat: check types yarn command and run on ci/cd

- src/app.ts
- src/authentication-flows/social.ts
- src/routes/tsoa/authorize.ts
- src/routes/tsoa/logout.ts
- src/routes/tsoa/passwordless.ts
- src/utils/validate-redirect-url.ts
- test/utils/validate-redirect-url.spec.ts
This would have saved us a lot of time :smile: 
Do we need some integration tests showing 
* when the origin doesn't match on a few different routes
* when the logout URL doesn't match on the logout route
* when the redirect URL doesn't match? (in the places it's used)
> fix: validate url function should return true/false

- src/adapters/planetscale/index.ts
- src/migrate/migrations/2023-11-16T14:27:00_passwords-table-password.ts
- src/migrate/migrations/index.ts
~I'm going to add migrations in this PR but I'll run them on a different planetscale branch~
~If we're going to run them on dev then I figure I should move the migration script into a branch going straight to `main` so we don't end up with migration conflict hell~ :smile: 
~*then* on this branch I can manually add my test passwords~
I just ran the migrations on planetscale dev so (as commented) if they're not ok, let me know!
----------------------
This is it working! 
On auth2 I suffix the passwords with `-auth2` to make sure we don't get false positives, that's why the first login *correctly* fails :+1: 
[Screencast from 2023-11-16 19-28-39.webm](https://github.com/sesamyab/auth/assets/8496063/346729df-818f-40a7-b2eb-6d8a688e035f)
> fix: password flow finished off here

- src/authentication-flows/social.ts
Fixed by pushing straight to dev
We probably don't want to keep persisting tokens so I'll keep investigating now
* `sub` or some unique ID: check these against Auth0
* google :heavy_check_mark: 
* apple
* facebook
* `profileData` fields
Examples from Auth0
Looking at Auth0 mgmt API results
All seem to have
```
email: "markus@ahlstrand.de",
email_verified: true
```
And some have other fields, quite different ones! (I'm assuming unique to each provider)
Google id_token - minus the comment id_token fields `iss`, `azp`, `aud`, `at_hash`, `iat`, `exp`
I think we could remove these fields and then write the rest
```
{
"iss": "https://accounts.google.com",
"azp": "195867377305-j00komjaq7etk3ua9oab69klhlli4uk7.apps.googleusercontent.com",
"aud": …
```
> fix: correctly write profile data

- src/authentication-flows/social.ts
Cleans up what we write to `profileData` on FB
> fix: strip out more fields from facebook id_token

- src/authentication-flows/social.ts
See my latest comment on the linked ticket if you want
Now Apple SSO is working :+1: 
Try `select * from users where profileData is not null;` in planetscale-dev and you'll see these new SSO users being created :muscle:
> fix: pluck more keys from apple id_token

- package.json
- src/authentication-flows/passwordless.ts
- src/authentication-flows/ticket.ts
- src/routes/management-api/users.ts
- src/routes/tsoa/dbconnection.ts
- src/routes/tsoa/login.ts
- src/utils/userIdGenerate.ts
- test/authentication-flows/ticket.spec.ts
- test/routes/tsoa/authorize.spec.ts
- test/utils/userIdGenerate.spec.ts
- yarn.lock
~Wrangler's `nanoid` is breaking everything. Doesn't actually have the functions needed to configure it. TBD~
I can't test this new function as everything explodes there (maybe some module issue)
*BUT* this actually works on Cloudflare :smile: 
See a new record I just made. Id - `85b1ada7f1b932c51aaf2b05`
> feat: stricter rules when generating user ids

- src/authentication-flows/social.ts
- src/types/User.ts
I think this makes sense
I'm not sure what would happen if the user actually changes their email address :exploding_head: 
*BUT* at least if they verify their email, we'll get this on the second sign in :sunglasses:
> feat: when signing in with sso pull email and email

- __mocks__/nanoid.ts
- test/authentication-flows/ticket.spec.ts
- test/routes/tsoa/authorize.spec.ts
- test/utils/userIdGenerate.spec.ts
I was doing this inline the test suites _but_ I should have added this to the existing nanoid `__mock__`
> test: mock nanoid in just one place

- src/authentication-flows/silent.ts
- src/routes/tsoa/authorize.ts
This will fix a *lot* of the errors we're getting on datadog
The `aud` in the `id_token` has to match the `client_id` else auth0.js gives an error
This also matches what happens with auth0.  Happy to demo this demo app further
Logging in is done per auth0 tenant. Logging in on one logs in on others. Logging out on one logs out on them all
[Screencast from 2023-11-27 12-17-47.webm](https://github.com/sesamyab/auth/assets/8496063/0a8540b2-aa6e-4f9d-8022-078b5b1a43b8)
We could investigate further what happens when different scopes are requested, but I think this is good for now :+1:
> fix: use client_id from request not from session state

- integration-test/flows/silent-auth.spec.ts
- integration-test/helpers/setup.ts
- integration-test/test-server.ts
We've had this regression a few times and it seems more sensible to do it extensively here on integration tests than login2 :sunglasses: 
It is sort of already done there but I can be sure of all the use cases here
> test: silent auth across different clients and tenants

- src/locales/en.ts
- src/locales/sv.ts
- src/locales/type.ts
Fixes
* login2 email snapshots failing because of a fullstop I removed :smile:   (what a spot) :heavy_check_mark: 
* english emails lacking header: :heavy_check_mark: 
This PR is snapshot tested by https://github.com/sesamyab/login2/pull/474 _(this is the last I'll push to auth2 dev)_
> fix: code emails final fixes

- integration-test/management-api/users-by-email.spec.ts
- integration-test/test-server.ts
- src/adapters/in-memory/users/getByEmail.ts
- src/adapters/interfaces/Users.ts
- src/adapters/kysely/users/getByEmail.ts
- src/authentication-flows/passwordless.ts
- src/authentication-flows/social.ts
- src/authentication-flows/ticket.ts
- src/routes/management-api/users-by-email.ts
- src/routes/management-api/users.ts
- src/routes/tsoa/authenticate.ts
- src/routes/tsoa/dbconnection.ts
- src/routes/tsoa/login.ts
This fixes our `getUsersByEmail` endpoint to match Auth0
*but more importantly* this PR is my first step towards signing on properly with different providers - we need a way to search by email _and_ provider
So I figure I'll KISS by returning _all_ users for a given email in the adapter
> feat: getUsersByEmail endpoint is plural

- integration-test/ping.spec.ts
- src/app.ts
Think I figured out the issue with hono testing. When we use the fluent api to create the router you get a typed version of the router. But.. like we did it before we created an empty router first and then added the routes. This way the router kept it's original type and the testing library didn't work.
Started by moving a single test and updated the main router. I'm not 100% sure this will work well with the tsoa routes? Maybe we just create a new instance of the router and it works?
If we get this working nicely we should be able to run the integration tests straight with bun which would be super fast, but we also could run the bun sqlite in-memory. That way we can finally drop the in-memory adapter.
> fix: switch to hono testing

- src/routes/tsoa/dbconnection.ts
We're missing *a lot* of `provider` and `connection` fields in our dev db
probably this is from migrations as our code is mostly correct
> fix: ensure connection and provider are set correctly on new signups

- integration-test/flows/social.spec.ts
- integration-test/mockOauth2Client.ts
- src/authentication-flows/social.ts
- src/routes/management-api/users.ts
Lol. This confused me. I found it while trying to reuse a util function to populate the identities
During the social signup I was writing the `profileData` to the primary user :facepalm: 
Then on the `GET/[id]` I was spreading in the profile data from the primary user to every linked account :joy: 
So the tests were passing
> bugfix: identities done wrong in two places

- integration-test/ping.spec.ts
- src/app.ts
- wrangler.toml
This is still early.. we should add a middleware that picks the tenantId from the sub or the header.
> fix: add subdomain support in dev

- integration-test/management-api/users-by-email.spec.ts
- integration-test/test-server.ts
- package.json
- src/authentication-flows/ticket.ts
- test/authentication-flows/ticket.spec.ts
- test/routes/tsoa/authorize.spec.ts
This looks like a bug to me! :smile: 
We were always returning a `nanoId()` for the `sub`
> fix: sub in access token should be user_id

- src/adapters/in-memory/clients/getClient.ts
- src/adapters/in-memory/clients/index.ts
- src/adapters/in-memory/domains/create.ts
- src/adapters/in-memory/domains/index.ts
- src/adapters/in-memory/index.ts
- src/adapters/interfaces/Domains.ts
- src/adapters/interfaces/index.ts
- test/fixtures/client.ts
- test/fixtures/context.ts
- test/services/getClient.spec.ts
I didn't implement `domains` when I changed the `getClient` in-memory data adapter to assemble `client` from the respective entities
I also had a skipped test checking this so I've brought this back
> fix: pull domains from in-memory adapter when building Client

- src/models/DefaultSettings.ts
- src/services/email/index.ts
- src/types/Client.ts
- src/types/sql/Domain.ts
- test/fixtures/client.ts
- test/services/getClient.spec.ts
Ooops we had the wrong column name in the SQL typescript type
Maybe we could have renamed the database field... but migrating the db always feels less clean
> fix: correct name domain columns

- src/authentication-flows/ticket.ts
In this case, the user record must not have a provider
I don't have access to planetscale production but *we really need to make sure all our prod users have providers set* (they'll be code if not set I think)
> fix: more descriptive error message if user not found

- src/routes/tsoa/login.ts
I made similar fixes to other routes
I'm not sure the signup route works correctly... If I signup with an email+password, and then I sign up again for the same email + different password - there's some error but I can't see it
Then neither work :thinking:
> fix: pass error in correctly to login render

- package.json
- yarn.lock
No issue with the upgrade actually
> fix: pin node types to 18.13

- integration-test/flows/code-flow.spec.ts
- integration-test/flows/social.spec.ts
- integration-test/management-api/users-by-email.spec.ts
- integration-test/mockOauth2Client.ts
- integration-test/test-server.ts
This was a legit bug we had on production for ages
By default, no tests should be in English or with English names, a bit like the survivors of a raid :sunglasses:
> test: swedish name with non-ASCII characters

- integration-test/management-api/users.spec.ts
- integration-test/setups/createTestUsers.ts
I removed that `setup()` helper that we weren't actually using (we weren't using any of the fixtures)
But I like the idea though. So I extracted out a common setup helper on the link tests
> test: helper functions to create fixtures

- __mocks__/nanoid.ts
- migrate/migrations/2022-12-11T09:17:35_init.ts
- migrate/migrations/2023-10-26T08:14:09_log_table.ts
- src/adapters/kysely/users/booleans.ts
- src/adapters/kysely/users/create.ts
- src/adapters/kysely/users/get.ts
- src/adapters/kysely/users/list.ts
- src/adapters/kysely/users/update.ts
- test/authentication-flows/ticket.spec.ts
- test/helpers/silent-auth-cookie.spec.ts
- test/integration/helpers/createTestUsers.ts
- test/integration/helpers/test-client.ts
- test/integration/management-api/users.spec.ts
- test/routes/tsoa/authorize.spec.ts
This moves the user integrations tests over to using the hono test library and a in-memory sqlite. Hopefully we can remove the in-memory adapter when all tests are moved over to the hono client.
We need to update the foreign keys for the users and the logs to make it work with sqlite.
> fix: user integration tests

- src/adapters/in-memory/clients/getClient.ts
- src/services/clients.ts
We had some old fallbacks for KV-storage and didn't pull the connections from the default settings correctly so we filtered out the connections added to a specific tenant.
> fix: refactor connections to support vipps

- src/services/clients.ts
So.. we still used a list of hard coded defaults. Missed that.
> fix: add back default settings

- src/services/oauth2-client.ts
It seems to be considered best practice to use basic auth for passing the client-id and the client-secret. Vipps only seems to accept this format.
> fix: use basic auth for token exchange

- migrate/migrations/2023-11-19T20:53:00_univeral-login-session.ts
- test/integration/flows/code-flow.spec.ts
This issue looks interesting...
If soloed, this test passes :heavy_check_mark: 
If ran with the previous test, it fails :x: 
The call to authorize to exchange the ticket doesn't give us the correct location header that we set in `applyTokenResponseAsQuery`
Instead we get `/u/login?state=testid-9`
> test: fixing second code flow test

- test/integration/flows/code-flow.spec.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/integration/flows/password.spec.ts
- test/integration/helpers/silent-auth.ts
using `typeof client` for the testing helper function - as discussed here https://github.com/sesamyab/auth/pull/383/files#r1442384913
> test: properly type client arg for silent auth helper function

- migrate/migrations/2023-11-02T23:18:12_sessions.ts
- migrate/migrations/2023-11-19T20:53:00_univeral-login-session.ts
- migrate/migrations/2024-01-11T10:58:00_missing-fields.ts
- migrate/migrations/index.ts
Edits done in https://github.com/sesamyab/auth/pull/403#event-11448207074 moved into new scripts
I'll rename my migration as https://github.com/sesamyab/auth/pull/409 had this number first
> fix: move existing edited new fields into new migration scripts

- src/routes/tsoa/domains.ts
Same issue we had on the connections route
> fix: tenant_id casing issues on patch routes when using `Partial`

- src/routes/tsoa/callback.ts
- test/integration/flows/social.spec.ts
A lot of SSO providers have _"back"_-style buttons that will then call us with 
https://auth2.sesamy.dev/callback?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied&state=eyJhdXRoUGFyYW1zIjp7InJlZGlyZWN0X3VyaSI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC9jYWxsYmFjayIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzdGF0ZSI6InJlZGlyZWN0X3VyaT1odHRwcyUzQSUyRiUyRmV4YW1wbGUuY29tJmNsaWVudF9pZD1zZXNhbXkmcmVzcG9uc2VfdHlwZT10b2tlbitpZF90b2tlbiZzdGF0ZT0xMjM0NTY3OCZjb25uZWN0aW9uPWF1dGgyIiwiY2xpZW50X2lkIjoic2VzYW15Iiwibm9uY2UiOiJHNzRfSHF2VXBjTHM4dlV1NUNycH5aUDdmeGNxVkUtNyIsInJlc3BvbnNlX3R5cGUiOiJ0b2tlbiBpZF90b2tlbiJ9LCJjb25uZWN0aW9uIjoiZmFjZWJvb2sifQ
We need to then redirect back on like Auth0 does
> fix: callback route can get error

- src/routes/tsoa/callback.ts
- test/integration/flows/social.spec.ts
I thought I'd manually tested this *but* now I've released everything, I've noticed I'm not passing back the original caller's state
> fix: pass back login2's state on error to /callback

- src/routes/tsoa/callback.ts
What we have released currently does work *but* better not to pass back `undefined` in the URL :+1:
> fix: dont pass undefined params back on error /callback

- src/routes/tsoa/authenticate.ts
- src/tsoa-middlewares/logger.ts
Matching Auth0
I'm not sure what will happen here because our logger only logs when `!!response.ok` :thinking:
> feat: log incorrect code as failed login

- src/routes/tsoa/passwordless.ts
- src/tsoa-middlewares/logger.ts
This is from tampering with the magic link and setting the wrong code.  So we get the same error logged by Auth0 as if we had entered the wrong code manually
> fix: correct error message on bad magic link redirect

- src/routes/tsoa/authenticate.ts
- src/routes/tsoa/passwordless.ts
- src/tsoa-middlewares/logger.ts
- test/integration/management-api/logs.spec.ts
Matching Auth0 logging with `cross origin login` 
*AND ALSO* I removed code login sent because Auth0 doesn't log that
> fix: correct log type for cross-origin login

- src/services/token-factory.ts
- test/integration/flows/code-flow.spec.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/integration/flows/password.spec.ts
- test/integration/flows/social.spec.ts
~I had to add a lot of extra destructuring... Maybe this is actually what our code is doing and the wrangler tests weren't running the whole flow...~
~Either way, I'll check what we get on production and investigate here~
Ahhhhhh, I hadn't considered this!
* In TypeScript we give the SQL datatypes optional keys to mean they can be `undefined`
* SQL doesn't `undefined`, it has `null`, so this is what is returned
And I think
* in our JS testing, if we get `undefined` back for a value, then the test doesn't complain if our expect object _doesn't_ have e.g. the key `foo: undefined`
_BUT_ it will complain about `foo: null` not being present
:exploding_head:
> fix: handling nulls coming from database

- migrate/migrations/2024-01-31T09:00:00_drop-logs-fields.ts
- migrate/migrations/index.ts
- src/adapters/interfaces/Logs.ts
- src/tsoa-middlewares/logger.ts
As discussed, I think we just one log type (called `event` on the Auth0 dashboard).  Using `/authorize` as an example, we have no idea what category this is when the method is called. It could be silent auth, a top level redirect, even a sign up
:exclamation: Requires migration script running on planetscale :exclamation: 
_ALTHOUGH_ it won't break anything if we don't run it for a while as it's just removing a field
~I'll change the logger function to not require a param initially. As mentioned on Slack~
~I will update auth-admin (along with other changes to the logs page to make it look more like Auth0)~
_Nah I disagree with this change. I started doing it but there are a lot of changes to make *and* it looks much tidier to use a decorator for the expected log type and description_
> fix: remove log field _category_

- src/helpers/apply-token-response.ts
- test/authentication-flows/ticket.spec.ts
- test/integration/flows/code-flow.spec.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/integration/flows/password.spec.ts
- test/integration/flows/social.spec.ts
- test/integration/login/code-flow-liquidjs.spec.ts
- test/integration/login/login-password.spec.ts
- test/integration/login/register-password-user.spec.ts
- test/routes/tsoa/authorize.spec.ts
- test/routes/tsoa/passwordless.spec.ts
I noticed this yesterday when playing around, that we're always putting the tokens into the querystring (which is then sent across the network)
If I'm pointing login2 to auth0 and I set `responseMode: "query"` when ` responseType: "token id_token"` _then_ on the call to `auth0/authorize` I get
The logs say `Unsupported response mode: query`
On login2 I'm not setting a `responseMode` so we should default to fragment, _BUT_ we could put in a check in auth2
> fix: return fragment by default

- src/helpers/apply-token-response.ts
- test/integration/flows/social.spec.ts
I figure we merge this and then I'll keep running the login2 playwright tests :see_no_evil:
> fix: uri encode state part of fragment

- src/adapters/kysely/logs/list.ts
We probably want to actually fix sorting on our mgmt API endpoints (although I haven't checked if Auth0 supports this)
_BUT_ for now, the easiest fix is to hardcode the logs to reverse date order
> fix: hardcode log sorting by date desc for now

- migrate/migrations/2024-02-05T18:35:00_log-desc-max-length.ts
- migrate/migrations/index.ts
- src/tsoa-middlewares/logger.ts
We were missing logs for a few reasons
As we're stringifying an object into `details`, the column wasn't long enough
> fix: get logging working

- src/routes/tsoa/authenticate.ts
- src/tsoa-middlewares/logger.ts
~I'm not sure if we can read the error message from inside the thrown description...~
~Maybe we need to catch the Hono HttpExceptions and then rethrow them...~
This works! On the global logs view we can see error logs coming through :smile: 
*I pushed this up to auth2 dev*
> feat: catch the HTTPException and log this

- src/adapters/interfaces/Connections.ts
- src/adapters/interfaces/Domains.ts
- src/adapters/kysely/connections/create.ts
- src/adapters/kysely/domains/create.ts
- src/routes/management-api/connections.ts
- test/integration/helpers/test-client.ts
`noUnusedParams` reminded me of this
When we call `create` on any of our data adapters, we pass the `tenant_id` in in two places, should we do this fix everywhere?
> fix: use tenant_id in adapter arg not in body

- src/authentication-flows/ticket.ts
I'm not sure how `main` got into a bad state as the CI/CD had ran on all the PRs...
I probably merged two in and we aren't forcing rebase of PRs. Which is fine. Just now and again we get this :smile:
> fix: import types properly

- migrate/migrations/2024-02-13T11:25:00_users-table-name-index.ts
- migrate/migrations/index.ts
Let's see if this fixes this
This must be from queries to the users list endpoint which filter by name and email (`LIKE` queries)
> chore: add index to name column on users table

- src/adapters/kysely/logs/list.ts
- src/adapters/kysely/users/list.ts
*PR description copy pasted from:* https://github.com/sesamyab/auth-admin/pull/111
In the Auth0 dashboard we have to manually write out queries e.g. `ip:"2a02:586:7a37:fa8c:e296:c2c1:a6:f4bc"`
I noticed though that we're not doing the users endpoint filtering correctly though as we've hardcoded any `q` param to be `user_id` or `user_name` but on Auth0 we actually query `q: name:dan* OR email:dan*` (as opposed to how we are just sending up the query e.g. `q:dan`
*SO* I figure I'll just hardcode IP address for now?
> feat: log filtering by ip

- src/routes/tsoa/authenticate.ts
- src/tsoa-middlewares/logger.ts
The middleware solution is very noisy and doesn't match what Auth0 does
> fix: make logging optional if no logtype passed in

- migrate/migrations/2024-02-19T20:14:00_users-email-constrain.ts
- tsoa.mjs
This update didn't really work. Process env will not be defined, it needs to be fetched from ctx.env which is a bit more complicated.
> fix: revert the authorize change

- test/integration/management-api/users.spec.ts
Let's not point fingers, but one of the devs on this project keeps breaking auth-admin!
Better to test in here than try and trigger playwright tests on auth-admin (which don't exist)
*BUT* how can we do a request with the correct headers and get the correct headers back? I haven't tried yet!
> TODO - test CORS headers for requests from auth-admin

- test/integration/flows/magic-link-flow.spec.ts
I was going to extract out way more but upon looking at this... I'm not sure if it's worth it. I don't want to write functions that include logic in tests :see_no_evil:
> test: extract out duplicate fixtures in magic link  tests

- src/routes/tsoa/passwordless.ts
- test/integration/flows/magic-link-flow.spec.ts
Ooops! :smile: 
*lucky I did what @markusahlstrand  asked* :smile: 
Login2 isn't testing a non-english incorrect code
I'll update the test on login2 as well to be in swedish
> fix: login2 expired code no locale subpath

- src/authentication-flows/social.ts
- src/utils/users.ts
- test/integration/flows/social.spec.ts
Note the first commit test actually fails. It's a bit of a synthetic test as in reality the first user added to the db would be the primary user *BUT* we shouldn't be relying on record-order in the database _especially_ given since we're filling the db with Auth0 data...
> feat: social get primary user

- test/integration/management-api/users.spec.ts
I've just noticed that we are `otherTenant` for the mgmt API users endpoint
We have a real danger of false positives here as we're populating this tenant with just one user, and then we're searching in different ways to return this same user...  so there's no actual difference between searching and returning all users for that tenant
*going forward* I would like to create another `getEnv` helper that adds 50+ randomish users to *really* test this (maybe some that are even similar), else we could really lose the battle for Troy!
> test: change every users test to use default tenant id

- migrate/migrations/2022-12-11T09:17:35_init.ts
- src/adapters/kysely/users/remove.ts
- test/integration/management-api/users.spec.ts
I think this is ready to go *BUT* currrently it's kind of already working as linked accounts don't appear when listing users... (they also shouldn't be searchable, which is something else we could fix)
I would like to actually confirm this by using Auth0 mgmt API
> fix: when deleting a primary account, also delete linked accounts

- src/routes/management-api/users.ts
- test/integration/flows/social.spec.ts
- test/integration/management-api/users-by-email.spec.ts
- test/integration/management-api/users.spec.ts
~We're throwing away params that we're receiving in the POST!~
Step 1. I'll do more PRs next as mentioned in the comments
> feat: use name if sent to user POST else fallback to email

- src/adapters/interfaces/Users.ts
- src/adapters/kysely/users/index.ts
- src/adapters/kysely/users/unlink.ts
- src/adapters/kysely/users/update.ts
- src/routes/management-api/users.ts
- src/types/User.ts
- test/integration/management-api/users.spec.ts
*LOL*.  If we pass `key: undefined` into kysely to update, we just ignore that :smile: 
Found while trying to do this PR! https://github.com/sesamyab/auth/pull/523
~I'm sure we had that issue elsewhere... At least on SQLite anyway~ :thinking: 
Indeed. We fixed this for the get users. SQL has no concept of `undefined`! where as `null` is tedious in typescript and means something different
So we're swapping `null` for `undefined` when reading
At some point we could do this for other fields because _we have no way to clear fields in auth-admin_
I don't see this as a huge issue for now so this PR does the minimum to fix what *may* be a production bug, but probably isn't :smile:   (I doubt we're unlinking accounts ever - I'd like to check our production logs to see which of the endpoitnts …
> test: fix unlinking accounts

- src/routes/management-api/users.ts
- test/integration/flows/social.spec.ts
- test/integration/management-api/users.spec.ts
fixes the get by id endpoint to *not* return linked users!
The dream of having tests that run against auth0 and auth2 would be amazing, as opposed to having to trust my screenshots :smile: 
~The linking accounts test fails when we unlink~ :exploding_head: 
~Interesting!  Maybe this exposes a bug there... I'll investigate now~ :thinking: 
Fixed on the destination branch of this PR :+1:
> test: do not return linked account on get by id endpoint

- src/routes/management-api/users-by-email.ts
- test/integration/flows/code-flow.spec.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/integration/management-api/users-by-email.spec.ts
This endpoint was already correctly not returning linked accounts (secondary accounts) *but* it was returning a 404 when it should return no results
> fix: emails endpoint should not 404 its a query

- src/routes/management-api/users.ts
- test/integration/management-api/users.spec.ts
Confirmed with auth0 management API
* see all comments on diff! More work to do on patching endpoint
* I'll reverse engineer a bit more and see how it handles the `PATCH` endpoint - if our implementation is correctly, I'll write tests. If not, I'll change it _and_ write tests
> fix: should not be able to patch a linked user

- src/routes/tsoa/dbconnections.ts
This creates the password reset route that auth0.js uses and just returns a success always :smile: 
~What do we actually send in the email?~
~And where do we send the user?~ :smile: 
~This is where Auth0 sends us~
~Do we want to send the user to the universal login? We'd need to match the styling on login2... so I figure sending them to login2 is better *BUT* then we need to decide how login2 should speak to auth2. I have an open PR where it uses the management API on an API route...~
I'll do this properly with universal login
Once I've got it working I can then write bun+sqlite tests here *AND* playwright tests on login2
We still need to get email validation working _but_ once that's done we can design how to do the least work possible styling this pages :sunglasses:
> feat: send password reset route that always returns success and does nothing :smile: 

- src/routes/management-api/users.ts
- test/integration/management-api/users.spec.ts
Confirmed behaviour on auth0. We already had this working so there's only a test here
> test: assert patching non-existent users returns a 404

- src/routes/management-api/users.ts
- test/integration/management-api/users.spec.ts
I wonder how much slower this will make the endpoint... As discussed, we want to do this in SQL to not have so many fetches _BUT_ the public won't be using this endpoint
> fix: list endpoint should return linked users

- src/routes/management-api/users.ts
- test/integration/management-api/users-by-email.spec.ts
We don't support username-password for production users, and it seems wrong that the profile service was doing this! (which has since been changed)
I'd rather throw an error so we know about this (see comments)
> feat: only allow email connections in POST to users endpoint

- src/authentication-flows/ticket.ts
- src/routes/management-api/users.ts
- test/integration/flows/password.spec.ts
- test/integration/flows/social.spec.ts
~This is a small PR *but*~ *LOL* not quite! Just this change requires substantial changes :partying_face: 
1. I want to confirm I'm going down the correct route here
2. We'll probably break the tests on dev on multiple projects (Which is fine!) so we can re-run all the playwright tests and manually set our test accounts to have their email verified :sunglasses: 
I'll try and get an email validation email working
> feat: return error message if email not verified on username-password

- migrate/migrations/2024-03-11T12:45:00_increase-otp-state-length.ts
- migrate/migrations/index.ts
- migrate/planetscale.ts
:exclamation: uncomment out the planetscale bit when running the production migration :exclamation: 
Else all the users midflow will lose their codes... which could cause problems for the next 30 mins :see_no_evil:
> fix: increase max length of otps state column

- src/authentication-flows/ticket.ts
I'm realising while fixing the tests on the password flow that it will be easier to use the primary user helpers everywhere first
> fix: ticket step - use primary user helpers in ticket flow

- src/routes/tsoa/login.ts
A glorious day! Final change done :partying_face: 
We've started actually doing the username-password implementation!
Passwordless has been fixed on another much smaller PR :ok: 
We fixed passwordless linking on another much smaller PR so I'll rebase this one now and see what else is left
In lots of cases this was correct as the first user added is the first user returned so, by definition, it is the primary account
*but* it was not always correct
We had an issue today on our CI/CD because one of the password logings was failing
We we're trying to find the user by an email lookup, but the using a newer code login user and then trying to find a password...
Which acts the same as though the password is invalid :sweat: 
I feel like we should
1. discuss each flow on this PR
2. probably break …
> fix: do not just take first `users.getByEmail` result as the account we want

- renovate.json
Renovate bot can never do this because it will never run on cloudflare :smile: 
Where are we actually using node if we're running on bun? We're using Node 18.13 as a way to enforce a JavaScript that will run on cloudflare right?
> chore: tell renovate bot to never upgrade node

- src/utils/users.ts
- test/integration/flows/code-flow.spec.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/integration/flows/social.spec.ts
~#### Next~
* ~rebase when https://github.com/sesamyab/auth/pull/547is merged, I think will still fail the same!~  :x:  as expected
--------------------------------------------------------------------------------------
* do sign up for an email _but not_ email verification
* sign up with social/code account with same email
* assert that not erroneously linked to unverified email account
*I'll do the fix for this here as well* :construction: :construction_worker: :building_construction: 
* do _another_ sign up with social/code (whichever didn't)
* verify that correctly linked to existing social/code
* then verify the email account and assert that linked to the primary account :upside_down_face:
> test: show that unverified password accounts are being linked to on social and code signups!

- src/routes/tsoa/login.ts
- test/integration/flows/password.spec.ts
I might have gone rogue here but we *definitely* don't want to block password resetting before the email is verified (else we will force the user to know their password to then send a new email validation email out!)
_and I'm also thinking_ if the user has clicked the password reset link... well we know they own their email address!
> feat: resetting password should be allowed on unverified accounts *AND* should also set the account as verified

- .gitignore
- package.json
- scripts/upload-css.sh
- src/app.ts
- src/utils/components/Layout.tsx
I just made these changes for the previous PR :sunglasses: 
Would be great to have some proper tests for this but we don't actually serve the real CSS file in our tests... so loading this output into playwright to render HTML would not make sense...
Going forward I can test this in the login2 playwright tests and read the *real* emails
> fix: rename css to tailwind everywhere

- package.json
- src/locales/en/default.json
- src/locales/it/default.json
- src/locales/nb/default.json
- src/locales/sv/default.json
- src/utils/components/Layout.tsx
- yarn.lock
This is actually a working solution for how to do translations in our React components :sunglasses: 
I've manually copied over these translation strings from `login2`.  We could also pull the login2 translation strings and use them in the React components...
*THOUGHTS?*  
https://github.com/sesamyab/auth/pull/594 I've gone ahead and pulled down the login2 translations on the next PR
> feat: translation strings in footer

- src/routes/tsx/routes.tsx
- src/utils/components/Layout.tsx
Check the footer! We have Swedish :smile: 
I'm pretty confident this solution is the way so I can do this for the rest of the text *I'll do this next*
> feat: switch translation based on tenant language

- src/authentication-flows/ticket.ts
- test/integration/flows/password.spec.ts
I wanted to put this new page on auth2 *BUT* it's inside a tsoa route so for now we can't (because we cannot return JSX inside tsoa)
Tandem PR => https://github.com/sesamyab/login2/pull/626
> feat: redirect to login2 unvalidated email page

- test/integration/jwks.spec.ts
Cool, now this works without any hacks and we can expose one app per api.
> fix: open api route from app

- src/app.ts
- src/middlewares/register-component.ts
- src/routes/swagger-ui.ts
- src/types/Env.ts
- wrangler.toml
Added a drop down to the docs page for the tsoa vs openapi spec pages. At some point we should separate the management api page and the oauth2 endpoints instead.
Added a kind of hacky middleware to get the authentication in. Haven't found a better way of doing it.
> fix: add separate api docs page for openapi

- src/app.ts
- src/routes/management-api/users.ts
- src/types/User.ts
I had to create an apple user and it was a bit of a pain since we only accepted email users. Was there a reason for this?
> fix: create user with apple

- src/app.ts
- src/routes/management-api/applications-fallback.ts
- src/routes/management-api/applications.ts
The old url structure doesn't really work with openapi. We need to pass the tenant-id in the header instead just like for auth0.
This PR adds a fallback route so we can move auth-admin of to the new paths. I don't map these to /api/v2 as they don't work like the auth0 routes.
> fix: application path

- src/adapters/interfaces/OTP.ts
- src/adapters/kysely/otps/index.ts
- src/adapters/kysely/otps/list.ts
- src/adapters/kysely/otps/remove.ts
- src/authentication-flows/passwordless.ts
- test/integration/flows/magic-link-flow.spec.ts
* magic link: :heavy_check_mark: 
What should we do here? There's a `used_at` field in OTPs so I'll set that to the current date *but*
* then I'll need to modify all the adapters to not select this
* we'll probably have to update the index on this table to include this field!
A. write failing test
B. fix implementation!
C. agree if this is the correct approach
* code login, codes as in the database entity..., tickets?... what else?
> fix: do not allow multiple use of magic links

- src/utils/userIdParse.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/utils/userIdParse.spec.ts
Some final console warnings from the user id parser
> test: use correct id format in tests

- .github/workflows/unit-tests.yml
This step can actually take a lot of time, especially the post-setupnode step
see this one. >50% of the test run is that
We already have Node 20 on the playwright docker image (and it seems quicker to use a docker image with node preinstalled than installing it after)
> test: do not need node setup

- test/integration/flows/magic-link-flow.spec.ts
This was previously in a test but then the fix to only allow single uses of login tickets meant this test was really a false positive
This is now actually asserting what we want on a fresh login ticket
> test: if email is altered then do not accept magic link as login

- src/routes/oauth2/passwordless.ts
- test/integration/flows/magic-link-flow.spec.ts
I have no idea if this worked at one point and we've had a regression or (also likely) by not actually testing the full flow this never worked :smile: 
I've just tested this running auth2 locally on wrangler
*this is the first of a few fixes and PRs* as we're not actually sending out a new email either :smile: 
I figure we should fix login2 first before we migrate this expired-code page to auth2 (which would be great)
> fix: pass on vendor id when redirecting to expired-code on login2

- src/adapters/kysely/clients/index.ts
- src/adapters/kysely/helpers/remove-nulls.ts
- src/adapters/kysely/users/list.ts
- src/app.ts
- src/routes/management-api/users.ts
- src/routes/swagger-ui.ts
- src/types/User.ts
- test/integration/flows/code-flow.spec.ts
- test/integration/flows/logout.spec.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/integration/flows/password.spec.ts
- test/integration/flows/silent-auth.spec.ts
- test/integration/flows/social.spec.ts
- test/integration/helpers/createTestUsers.ts
- test/integration/helpers/silent-auth.ts
- test/integration/jwks.spec.ts
- test/integration/keys.spec.ts
- test/integration/login/code-flow-liquidjs.spec.ts
- test/integration/login/code-flow.spec.ts
- test/integration/login/forgot-password.spec.ts
- test/integration/login/login-password.spec.ts
- test/integration/login/register-password-user.spec.ts
- test/integration/management-api/logs.spec.ts
- test/integration/management-api/tenants.spec.ts
- test/integration/management-api/users-by-email.spec.ts
- test/integration/management-api/users.spec.ts
- test/integration/userinfo.spec.ts
Split the api's in a separate for the oauth endpoints and the management api.
When doing this I noticed that he user endpoints weren't returning the correct content-type which in turn generated loads of errors. A bit surprising that the code has worked before.. We were doing unsafe typecastings that now are replaced by zod-parsing. There's still a bit of cleanup required to make all the the types match correctly, but think this is a good step on the way.
> fix: refactor routes and fix users

- src/authentication-flows/ticket.ts
- test/integration/flows/password.spec.ts
Set the last login user info for the ticket flow. A few things I'm not sure about:
- This will probably update the update_at field of the user, which doesn't feel great. Maybe we should have a separate "register login" function in the adapter that only sets the last-ip and the login count? 
- This only applies to the ticket flow. Would be great to have a single point for this code that also applies to social auth flow.
> fix: set last login for ticket flow

- src/styles/tailwind.ts
Ooops, I totally forgot that I need to run `scripts/build-tailwind-css.sh` to then put the generated CSS into the typescript file
I think the scripts folder should be for things that can't be done as scripts in package.json... :thinking: 
We probably also want this done on the CI/CD on a build step that crashes if it's changed.
When I made this script I just did the quickest thing as I didn't believe this would actually work :smile: 
Comments/boss-level direction welcome :saluting_face:
> chore: update tailwind

- src/utils/components/LoginWithCodePage.tsx
Ouch, we have so many tests but of course none of them actually act like a user and use the web form :smile:
> fix: use correct form element name

- build-tailwind.js
- scripts/build-tailwind-css.sh
- src/app.ts
- src/styles/tailwind.ts
- src/utils/components/Layout.tsx
- tailwind.config.js
:partying_face: 
This is what it looks like now when running locally
*BUT* I'll have to update the snapshots only when this is merged, as in the playwright snapshot helper I'm doing 
```
const responseBody = responseText.replace(
"/css/tailwind.css",
"http://auth2.sesamy.dev/css/tailwind.css",
);
```
Which will only be updated *after* merging this of course
It's not ideal *BUT* after this we shouldn't have to make any major tailwind CSS changes... so there should only be a few cases of this.
> fix: auth2 pages now styled like login2

- src/routes/tsx/routes.tsx
`passwordless/verify_redirect` requires a `nonce` param and we're not adding that to the magic link on the universal auth `POST` `/u/code` (where we send the code email)
> fix: add nonce to magic link on universal auth flow so works

- src/services/oauth2-client.ts
- src/services/token-factory.ts
This should fix the tests on login2. This is me running login2 against auth2 locally and I made fixes until it stopped complaining :smile:
> fix: put exp and iat back into ID tokens

- src/app.ts
- src/routes/management-api/applications.ts
- src/routes/management-api/connections.ts
- src/routes/management-api/domains.ts
- src/routes/management-api/keys.ts
- src/routes/management-api/logs.ts
- src/routes/management-api/tenants.ts
- src/routes/management-api/users-by-email.ts
- src/routes/management-api/users.ts
- src/routes/oauth2/callback.ts
- src/routes/oauth2/well-known.ts
- src/routes/tsx/routes.tsx
Rename for consistency. Appending the name with routes solves some of the name conflicts we had before.
> chore: rename routes

- .github/workflows/unit-tests.yml
- src/utils/components/LoginEnterCodePage.tsx
This is in all the Nextjs repos. I copy-pasted it from a Gleb Bahmutov blog article, but now I understand what it does
If one step failures then I would expect the other steps not to run *unless* we specify e.g. `always()`
See penultimate commit!
> test: only upload snapshots on failure

- test/integration/login/code-flow-liquidjs.spec.ts
I expected this one to fail *BUT* it of course works as we're already selecting the primary user in the user helpers
> test: universal auth code flow existing linked user

- test/integration/login/code-flow-liquidjs.spec.ts
~Wow, this test actually does fail~ :smile: 
~This was one flow that I expected to _"just work"_~ :sunglasses: 
I fixed this on https://github.com/sesamyab/auth/pull/803 Wasn't a real bug as such, just returning the wrong status code while returning an error message in the JSX template
> test: that can not reuse code

- .github/workflows/unit-tests.yml
We aren't actually running the tests after updating `main`. So we could have situations where `main` has failing tests because we aren't forcing PRs to be up-to-date before merging them (and I don't think we should it can become a nightmare :smile: )
We aren't doing anything here though if main fails, I just keep an eye on it when merging lots of PRs
> test: run tests on every push

- src/utils/components/LoginEnterCodePage.tsx
- src/utils/components/LoginWithCodePage.tsx
There are a few cases where we block the CTA button if something is not filled e.g. code entry, email entry
I'll do the code on this PR *BUT* ~I think I'll need JavaScript~ :smile:   *no actually* :thinking:   This can be done just using HTML5 form validation
This is probably better UX even though it might not be on brand (the validation messages are native to the browser)
Comments welcome. We could ask the other frontenders what they think
This is still an improvement!
> feat: HTML5 form validation required fields

- src/utils/components/LoginWithCodePage.tsx
I get the feeling I never use the native input types because they don't play well with React e.g. the `onChange` event is only fired after a change results in a valid value
*but* we're not using any clientside JS...
> fix: set email input to type email

- test/integration/flows/password.spec.ts
- test/integration/helpers/test-client.ts
- test/integration/login/code-flow-liquidjs.spec.ts
- test/integration/login/login-password.spec.ts
- test/integration/login/register-password-user.spec.ts
I'm doing this first before then getting `vendor_id` from the params passed to `/authorize` on  https://github.com/sesamyab/auth/pull/818
> test: have mock vendor settings fetcher return vendor settings based on param

- src/token-grant-types/authorizationCodeGrant.ts
`/oauth/token` should return JSON e.g.
But we were returning a redirect with the tokens appended to the URL e.g. the implicit flow
Looks working locally now :smile: 
I'll force merge this if the tests pass
*AFTER*
we should
* write tests for this
* do the same change on the other token flows
> fix: return tokens not doc

- src/routes/tsx/routes.tsx
- test/integration/login/register-password-user.spec.ts
We should be returning 400s for all JSX error pages (I've gone through manually and checked)
> fix: return 400s for other error routes

- src/styles/tailwind.ts
- src/utils/components/Button.tsx
This is what Auth0 does on their universal login forms.  This seems fine to me, it gives the impression that something happens, and the requests shouldn't take _that_ long
[Screencast from 2024-05-23 10-17-35.webm](https://github.com/sesamyab/auth/assets/8496063/5e32bd4c-20ab-4b5b-915d-ed5ee590ba89)
The colour isn't on brand though it's just copied from https://tailwindcss.com/docs/hover-focus-and-other-states#hover-focus-and-active
> feat: add focus state to button

- src/utils/components/ForgotPasswordPage.tsx
- src/utils/components/SignUpPage.tsx
Seems pretty low hanging fruit to force the user to enter an email before hitting submit
We're using an email input on the first step
> feat: use required email inputs

- migrate/migrations/2024-05-24T16:25:00_increase-universal-auth-state-length.ts
- migrate/migrations/index.ts
I checked on planetscale and I don't see any other tables with such a short state field
> feat: migration universal auth state field to long

- test/integration/login/code-authorization.spec.ts
- test/integration/login/pkce.spec.ts
This doesn't look tested anywhere, thus why we had the issue with the token service not being able to read the tokens from the hash fragment :smile:
> test: code authorization flow

- src/utils/components/LoginEnterCodePage.tsx
As Markus pointed out, after multiple form submissions, the back button will go back to the browser state in the previous form submission
> fix: back button goes to first step

- src/routes/tsx/routes.tsx
Fixes this issue
[Screencast from 2024-05-31 17-22-57.webm](https://github.com/sesamyab/auth/assets/8496063/eeee95c5-1758-457f-abe7-923fd52b5fc1)
* sadly they don't actual test a real flow so I can't write a test to show that this flow was broken (although we could inspect the session)
* I'll remove the `username` querystring param and I'll always read the `username` from the state
> fix: add username to state before changing page

- src/routes/tsx/routes.tsx
- test/integration/login/code-flow-liquidjs.spec.ts
As requested on https://github.com/sesamyab/auth/pull/870 - was easier to recreate the PR
We should manually A/B test this before and after merging
This is me running it on wrangler locally... I think it's marginally quicker. I prefer using machines to measure though :smile: 
[Screencast from 2024-06-03 11-41-16.webm](https://github.com/sesamyab/auth/assets/8496063/740fc4ac-7ab2-4e60-b75e-82e49d962a70)
> fix: waitUntil when sending code/link email on universal auth to improve time to next page

- src/utils/components/ForgotPasswordPage.tsx
- src/utils/components/Form.tsx
- src/utils/components/Layout.tsx
- src/utils/components/LoginEnterCodePage.tsx
- src/utils/components/LoginPage.tsx
- src/utils/components/LoginWithCodePage.tsx
- src/utils/components/ResetPasswordPage.tsx
- src/utils/components/SignUpPage.tsx
This fixes the bug we have where we don't actually submit the form, but I show a spinner because the button is clicked
[Screencast from 2024-06-03 19-08-48.webm](https://github.com/sesamyab/auth/assets/8496063/55b50022-331b-4408-935c-8dbcea313066)
[Screencast from 2024-06-03 19-09-38.webm](https://github.com/sesamyab/auth/assets/8496063/0129a7ed-d84a-4b36-a29b-d5a51635602d)
That works so much better right? :smile:
> fix: button spinner on form submit

- migrate/migrations/2024-06-03T10:00:00_disable-sign-ups.ts
- src/routes/management-api/applications.ts
* default value for `disable_sign_ups` in SQL migration
* type coercion when getting an application on `disable_sign_ups` field
> fix: disable_sign_ups fixes

- migrate/migrations/2024-06-05T10:00:00_otp-ip-address.ts
- migrate/migrations/index.ts
- src/adapters/kysely/otps/list.ts
- src/authentication-flows/passwordless.ts
- src/routes/oauth2/passwordless.ts
- src/routes/tsx/routes.tsx
- src/tsoa-middlewares/logger.ts
- src/types/OTP.ts
- test/integration/flows/code-flow.spec.ts
- test/integration/flows/magic-link-flow.spec.ts
- test/integration/login/code-flow-liquidjs.spec.ts
Ok, this does two (or three...) things again:
- It adds the IP address to the OTP codes so we can use that to validate that the IP hasn't changed. It doesn't actually do the validation yet
- It disables the stamping of the used_at field if you use the magic link flow. I would prefer if we can validate this by IP instead, but.. maybe we start here and add more logs to see what the impact would be
- Added a log for successful calls.
> fix: skip disabling the code for magic links

- src/controllers/email.ts
- src/routes/oauth2/passwordless.ts
- src/routes/tsx/routes.tsx
- src/utils/magicLink.ts
This seems the lowest hanging fruit for de-duplicating repeated code for sending code emails. We have enough code coverage and snapshots of emails that the :heavy_check_mark:s are enough for me :+1: 
I still need to send at least one more code email (when clicking the _use a code_ button on the password page)
> feat: extract out magic link helpers

- src/components/EnterCodePage.tsx
- src/components/EnterEmailPage.tsx
- src/components/EnterPassword.tsx
- src/components/EnterPasswordPage.tsx
- src/routes/tsx/routes.tsx
Seems a sensible thing to do. The names don't bear relation to what the steps do now and it always takes me a moment to remember which is which
I wouldn't mind renaming the routes as well as `/u/code` is the email entry step
> chore: rename components

- src/authentication-flows/ticket.ts
- src/routes/oauth2/authenticate.ts
- src/tsoa-middlewares/logger.ts
- test/integration/flows/code-flow.spec.ts
After doing a code login on login2 pointing to auth0, we get these logs on the user object
On auth2 currently we get *nothing* it seems :smile: 
I would rather be explicit than go down the middleware approach *BUT* we did have logging working with the middleware approach  :thinking:   Was this a tsoa thing that doesn't work now?
> feat: log scoa after x-origin code login

- src/routes/oauth2/logout.ts
- test/integration/flows/logout.spec.ts
We're not actually using this route on universal login because we aren't checking for silent auth cookies there (at least for now)
Still, logouts from login2 are live on production and tunnelled through the token service I believe!
> fix: explicit log of slo

- test/integration/flows/password.spec.ts
We were already logging this on the last PR (by logging any successful ticket auth as `scoa` ... which is correct I'm sure)
So this PR is just asserting this
> test: assert xorigin password logins are also logging scoa

- src/routes/oauth2/dbconnections.ts
- test/integration/flows/password.spec.ts
We probably won't ever use this endpoint on production *BUT* Auth0 Universal auth doesn't have code logins, so I'm checking what it logs for code sign ups on the auth0.js endpoints and copying that
Turns out there is no `success signup` event for a new code user. We simply get a `successful login/x-origin login` event
> feat: success signup dbconnections

- src/routes/tsx/routes.tsx
- test/integration/breakit-customizations.spec.ts
Auth0 Universal Auth doesn't have this flow with an email entry on the first step to then go to a code login
Password sign ups are disabled by hiding the button as done on https://github.com/sesamyab/auth/pull/938
The only log I get on auth0 is when trying to use the `/passwordless/start` endpoint after disabling signups for `email` on Auth0, which then gives us this log!
> feat: log disabled signup

- src/routes/oauth2/dbconnections.ts
- src/routes/tsx/routes.tsx
- test/integration/flows/password.spec.ts
- test/integration/login/login-password.spec.ts
- test/integration/login/register-password-user.spec.ts
Now we have this live I'm checking which logs don't appear tied to users or anything else in auth-admin :+1: 
And I missed Ids off most of the new logs.  This is now fixed so they should appear like on the auth0 dashboard
> fix: fixing logs after releasing and QAing

- src/authentication-flows/social.tsx
- test/integration/breakit-customizations.spec.ts
There are a few calls like `ctx.set("logType", "fsa")` which used to log when we had the logging middleware working on tsoa
This PR fixes the social login to explicitly logs
> fix: log on social sign on errors

- src/authentication-flows/social.tsx
- test/integration/breakit-customizations.spec.ts
~*this is currently deployed to dev*~ Nope! Previous PR merged so now `main` is back on auth2.sesamy.dev :+1: 
[Screencast from 2024-06-14 11-36-59.webm](https://github.com/sesamyab/auth/assets/8496063/1958ef0a-dbfc-4616-b1b4-8a3ba530bcd3)
:smile: I don't actually think we should do this :smile: 
Although I'm convincing myself maybe we should
> fix: if login2 is the caller, then ignore `disable_sign_ups` check

- src/authentication-flows/ticket.ts
- src/routes/tsx/routes.tsx
- test/integration/flows/password.spec.ts
- test/integration/login/login-password.spec.ts
I'm making this one up because Auth0 has no built-in email verification functionality (correct me if I'm wrong!)
I'm guessing at which log type https://auth0.com/docs/deploy-monitor/logs/log-event-type-codes
But this seems a reasonable thing to log for visibility
> fix: log failed login when email not verified

- src/components/DisabledSubmitButton.tsx
This makes the playwright testing a nightmare :smile: 
This is because of the hack to get the button in the loading state...
> fix: do not duplicate button children

- src/components/DisabledSubmitButton.tsx
In a previous fix I removed the duplicate text https://github.com/sesamyab/auth/pull/953
But we want whitespace there else the button is reduced in height (very obvious now on dev)
We could snapshot this button state... I could click it when we load the HTML into playwright :thinking:
> fix: ooops need whitespace for button height

- src/authentication-flows/social.tsx
- test/integration/flows/social.spec.ts
this should fix them appearing for e.g. this user https://auth-admin.sesamy.com/fGsqCfBjXixQrYKCnBIPl/users/google-oauth2%7C108791004671072817794/1
I can QA once merged
> fix: log user ids for social accounts on success signup & login

- src/authentication-flows/password.ts
- src/routes/oauth2/authenticate.ts
- src/routes/tsx/routes.tsx
- test/integration/flows/password.spec.ts
- test/integration/helpers/test-client.ts
- test/integration/oauth/authenticate.spec.ts
- test/integration/oauth/token.spec.ts
Use the same login for the /co/authenticate endpoint which was interesting.. I had to add a param to change the email_validation to "disabled" as our current tests wouldn't work otherwise.
The last step will be to move the logging up to the auth-flow function as well and it will work for both endpoints.
> fix: login flow for authenticate

- migrate/migrations/2024-07-15T10:00:00_user_id.ts
- migrate/migrations/index.ts
- src/adapters/kysely/users/create.ts
- src/types/User.ts
Step one of migrating to using user_id as primary key. Once this is migrated we can copy all the id's and making this field required.
> fix: add user_id column

- src/authentication-flows/silent.ts
- src/authentication-flows/social.tsx
- src/authentication-flows/ticket.ts
- src/authentication-flows/universal.ts
- src/helpers/generate-auth-response.ts
- src/routes/oauth2/authorize.ts
- src/routes/oauth2/callback.ts
- src/routes/oauth2/passwordless.ts
- src/services/cookies.ts
- src/token-grant-types/authorizationCodeGrant.ts
- test/integration/login/code-authorization.spec.ts
The new functionality is that the authorize endpoint checks if the current session matches with the login_hint and in that case it returns to the redirect_url directly.
> fix: add silent auth for login hint

- src/authentication-flows/silent.ts
- src/authentication-flows/social.tsx
- src/authentication-flows/ticket.ts
- src/authentication-flows/universal.ts
- src/components/CheckEmailPage.tsx
- src/components/Form.tsx
- src/components/Trans.tsx
- src/helpers/generate-auth-response.ts
- src/routes/oauth2/authorize.ts
- src/routes/oauth2/passwordless.ts
- src/routes/universal-login/routes.tsx
- src/token-grant-types/authorizationCodeGrant.ts
- src/token-grant-types/clientCredentialsGrant.ts
- src/token-grant-types/pkceAuthorizeCodeGrant.ts
- test/integration/helpers/test-client.ts
- test/integration/login/silent-auth.spec.ts
Added a new check-account page to handle the "do you want to continue with..." dialog. Also add a Trans component similar to what exists in react-i18n, but for hono jsx. 
Refactored a bit in the generateAuthResponse method to take the client instead. Think it makes it easier and we now create the silent auth tokens as part of this function as well.
> feat: add a check account page for silent auth

- src/authentication-flows/passwordless.ts
- src/authentication-flows/universal.ts
- src/routes/oauth2/authorize.ts
- src/utils/getSendParamFromAuth0ClientHeader.ts
Add support for setting both the login_hint and connection = email to end up straight on the code verification page. Refactored the code to separate the sendOtpEmail to a flow, but haven't yet replaced the other code-paths.
> feat: support login-hint and email connection

- src/authentication-flows/universal.ts
- src/helpers/generate-auth-response.ts
- src/helpers/silent-auth-cookie.ts
- src/routes/management-api/prompts.ts
- src/routes/oauth2/authorize.ts
- src/routes/oauth2/token.ts
- src/routes/universal-login/routes.tsx
- src/token-grant-types/authorizationCodeGrant.ts
- test/integration/login/login-hint.spec.ts
- test/integration/login/ui-locale.spec.ts
Fix so that the login_hint codes are generated with a reference to the universallogin session rather than the token session
> fix: login hint with code
