sesamyab/auth

src/authentication-flows/silent.ts
src/authentication-flows/social.ts
src/authentication-flows/ticket.ts
src/authorization-grants/authorizationCodeGrant.ts
src/helpers/generate-auth-response.ts
src/helpers/silent-auth-cookie.ts
src/routes/tsoa/authorize.ts
src/routes/tsoa/token.ts
test/authentication-flows/silent.spec.ts
test/authentication-flows/ticket.spec.ts
test/routes/tsoa/authorize.spec.ts
test/test-helpers/mocked-context.ts

So, it's not really working yet but one step closer..

fix: make response type optional

---

.github/workflows/unit-tests.yml
package.json
src/routes/tsoa/tenants.ts
src/services/datadog.ts

I see formatting changes included on the other PR :smile:

feat: lint and prettier ci cd

---

src/authentication-flows/universal.ts
src/errors.ts
src/models/State.ts
src/models/User.ts
src/routes/tsoa/login.ts
src/templates/reset-password.liquid

A bunch of stuff that was breaking when switching to use state

fix: password reset flow

---

src/models/User.ts
src/routes/tsoa/login.ts
src/routes/tsoa/users.ts
src/templates/code.liquid
src/templates/enter-code.liquid
src/templates/render.ts
src/types/LoginState.ts

So, this is the same as the other pr. It's a universal login version of the code flow which we likely won't use once login2 is done. But.. at least it works and it's possible to sign in. The universal auth doesn't use the api endpoints so it's slightly different to how login2 will work.

feat: code flow in universal auth

---

src/helpers/generate-auth-response.ts
src/services/token-factory.ts
yarn.lock

I think this should fix a lot of the failing tests on login2

feat: put email into id token

---

.github/workflows/unit-tests.yml

This _correctly_ fails currently as the build is failing :smile:

feat/build on CI/CD

---

src/routes/tsoa/logout.ts

This matches what the auth0 libraries do

feat: auth0 returnTo param

---

.github/workflows/unit-tests.yml
src/authentication-flows/ticket.ts

Pass the redirect_uri to the authParams

fix: redirect_uri for ticket flow

---

.github/workflows/unit-tests.yml
src/authentication-flows/ticket.ts
test/authentication-flows/ticket.spec.ts

This is to show the test was incorrect for the ticket flow, Markus' PR will fix this (when the tests run on that :thinking: )

test: failing test to show we are not getting redirect_uri from param

---

src/hooks/migrate-password.ts
src/migrate/migrations/2023-06-20T12:07:25_migrations.ts
src/migrate/migrations/index.ts
src/models/User.ts
src/routes/tsoa/migrations.ts
src/types/index.ts
src/types/sql/Migration.ts
src/types/sql/db.ts
src/types/sql/index.ts

Added a migration table where you can add migrations for connect-id or auth0. It will check these services if you try to login with password but there's no password hash stored.

feat: add migrations for auth0

---

src/constants.ts
src/helpers/content-range.ts
src/middlewares/cors.ts
src/routes/tsoa/applications.ts
src/routes/tsoa/connections.ts
src/routes/tsoa/dbconnection.ts
src/routes/tsoa/migrations.ts
src/routes/tsoa/tenants.ts
src/routes/tsoa/users.ts

Added headers for range the way that react-admin wants it. It's not really correct as the returned range doesn't show the correct count.

feat: add headers for react-admin

---

package.json
src/models/User.ts
src/routes/tsoa/connections.ts
src/routes/tsoa/login.ts
src/routes/tsoa/users.ts
src/token-grant-types/passwordGrant.ts
src/types/Client.ts
src/types/sql/Connection.ts
src/types/sql/db.ts
test/models/User.spec.ts
yarn.lock

Oops. Updated the packages in the same PR again..
Finally figured out why the email validation kept flipping back :)

fix: email validation

---

src/errors.ts
src/routes/tsoa/authorize.ts
src/routes/tsoa/logout.ts
src/services/clients.ts
src/types/Client.ts
src/types/sql/Connection.ts
src/utils/validate-redirect-url.ts
test/fixtures/context.ts
test/routes/tsoa/token.spec.ts
test/utils/validate-redirect-url.spec.ts

Various fixes and improvements to the url checks

fix: improve redirect validation

---

.github/workflows/release.yml
tsoa.mjs

fix: update ci for prod

---

src/controllers/email.ts
src/hooks/update-client.ts
src/migrate/migrations/2023-08-22T15:06:26_dkim.ts
src/migrate/migrations/index.ts
src/routes/tsoa/domains.ts
src/routes/tsoa/tenants.ts
src/services/email.ts
src/types/Client.ts
src/types/sql/Domain.ts
test/fixtures/context.ts
test/routes/tsoa/token.spec.ts

Adds dkim to the fetch requests if available.

feat: add dkim to emails

---

jest.setup.js
src/helpers/pkce.ts
src/server.ts
src/types/Env.ts
test/fixtures/context.ts

Saw this when doing the jwt stuff. By adding subtle to the global namespace and using node 20 we can remove a bunch of fixtures. I'll start with hash and do the token stuff next.

chore: with node 20 web crypto is available

---

.github/workflows/release.yml
src/authentication-flows/social.ts
src/services/clients.ts
src/types/Client.ts

Did a bit of refactor of the zod schemas and added a try/catch for the connection validation

fix: handle invalid connections

---

.gitignore
yarn.lock

On `main` when I run `yarn` I get a new lock file. Do you also get this @markusahlstrand ? :thinking: 
I would assume the build would fail somewhere.  I'm on Node v20 (as per the `.nvmrc` file)

feat: update yarn lock

---

src/services/clients.ts

Did a separate PR to just add the issuer to the callbacks to make it easier to test with the universal auth.

feat: add issuer callbacks to the defaults

---

src/migrate/migrations/2023-08-28T09:12:44_styles.ts
src/migrate/migrations/index.ts
src/types/sql/Tenant.ts

Added some styles properties on the tenant

Tenant styles

---

src/models/User.ts

Step 1! next i'll do https://app.shortcut.com/sesamy/story/4264/resend-the-email-if-a-new-code-requested-within-30-minutes-and-extend-the-ttl

feat: login code now valid for 30 mins

---

src/models/User.ts
test/models/User.spec.ts

Ooops!  Lucky we're not using this on prod else that would have been a bug :smile:

feat: unit tests createAuthenticationCode AND fix logic

---

jest.setup.js
package.json
src/server.ts
src/services/email/EmailOptions.ts
src/services/email/mailchannels.ts
src/services/email/mailgun.ts
src/types/Env.ts
test/fixtures/context.ts
test/services/email/mailgun.spec.ts
yarn.lock

So far it's not used but it adds the service.
This PR adds a jest fetch mock which will be pretty convenient for other tests.

feat: add mailgun support

---

.env.template
jest.setup.js
package.json
src/server.ts
src/services/clients.ts
src/services/email/EmailOptions.ts
src/services/email/mailchannels.ts
src/services/email/mailgun.ts
src/types/Env.ts
test/fixtures/context.ts
test/services/email/mailgun.spec.ts
test/services/getClient.spec.ts
yarn.lock

Added a set of defaults for connections like well-known strings for facebook, google and apple. This way we only need to add the client-id's and secrets in the env.

feat: added static default settings to make env a bit slimmer

---

src/migrate/migrations/index.ts

fix: add the mailgun migration

---

src/hooks/update-client.ts

So, we need to remove any null values. We should add a kysely-fix for this..

fix: handle null in tenant

---

src/controllers/email.ts
src/types/Client.ts
test/routes/tsoa/passwordless.spec.ts

This _should_ fix the email logo sending issue :smile:

feat: correct types for logo

---

.gitignore
scripts/upload-users.js
src/handlers/update-user.ts
src/models/User.ts
src/routes/tsoa/users.ts
src/server.ts
src/services/events.ts
wrangler.toml

- Changed the updateUser handler so it also can delete users.
- Added a delete endpoint for users
- Added a script for importing users from a auth0 json dump.

feat: added a script for importing useres and a user delete endpoint

---

src/helpers/sql.ts
src/routes/tsoa/applications.ts
src/routes/tsoa/connections.ts
src/routes/tsoa/domains.ts
src/routes/tsoa/members.ts
src/routes/tsoa/migrations.ts
src/routes/tsoa/tenants.ts
src/routes/tsoa/users.ts
src/server.ts

Added a helper to fetch the ranges correctly.

feat: add helper for ranges

---

scripts/import-users.js

Think we lost the import file in git somehow..

feat: add back import script

---

src/errors.ts
src/helpers/sql.ts
src/models/User.ts
src/routes/tsoa/tenants.ts
src/routes/tsoa/users.ts
wrangler.toml

Found a bug in the api when you weren't logged in with a admin user.. We did a double select. Skipped the join to make it simpler :)

tenant fix

---

src/routes/tsoa/token.ts
src/token-grant-types/authorizationCodeGrant.ts
test/routes/tsoa/token.spec.ts

Lots of copy-pasting from the token service :smile:

feat: implement client credential flow in auth2

---

src/routes/tsoa/users-mgmt.ts

feat: implement get user by email - management API

---

src/routes/tsoa/users-mgmt.ts

feat: implement create user by email - management API 

---

src/controllers/email.ts
src/hooks/update-client.ts
src/routes/tsoa/tenants.ts
src/types/Client.ts
test/fixtures/context.ts
test/routes/tsoa/token.spec.ts
test/services/getClient.spec.ts

The structure of the client was a bit odd due to the table join. Change to fetch the client separtely and moved the client under the tenants. Also fixed so the client is written on tenant updates.

fix: update the format client

---

package.json
src/models/State.ts
src/models/User.ts
test/fixtures/context.ts
test/models/User.spec.ts
yarn.lock

Bumped the version of the tRPC lib and passed the Env to make it typed.

fix: updated trpc proxy to get typed env

---

src/routes/tsoa/users-mgmt.ts

I'll do any changes here requested on earlier PRs (then I can do the same changes everywhere)

feat: feedback from previous PR reviews

---

src/models/User.ts
src/routes/tsoa/users-mgmt.ts
src/routes/tsoa/users.ts
src/types/Client.ts

This looks working now!  We have CRUD  
[Screencast from 2023-09-08 12-39-43.webm](https://github.com/sesamyab/auth/assets/8496063/3fc3d568-9dbc-4710-af2c-ed5051e1c7a1)

feat: implement delete user by email - management API 

---

src/helpers/generate-auth-response.ts
src/routes/tsoa/token.ts
src/server.ts
src/token-grant-types/passwordGrant.ts
src/token-grant-types/passwordlessGrant.ts
src/types/Client.ts
test/helpers/generate-auth-tokens.spec.ts
test/token-grant-types/passwordGrant.spec.ts
test/token-grant-types/passwordlessGrant.spec.ts

We didn't pass on the audience from the request correctly. Added tests for the grant flows as they were missing as well.

fix: fetch audience from request

---

src/routes/tsoa/users-mgmt.ts

We don't have enough users in any client to test this
*BUT* I could do that next in the test client (with the auth0 management API `createUser()` working I can quickly add *a lot* :smile:

feat: add range to users-mgmt index route

---

src/routes/tsoa/users-mgmt.ts

We can add this now I know the endpoints are sort of working :smile:

feat: set security on new management api routes

---

src/models/User.ts
src/routes/tsoa/users-mgmt.ts
src/types/Profile.ts

Added a call so that the linked user gets a `linked_with` field set in the profile.

fix: add linking of both users

---

src/controllers/email.ts
src/models/DefaultSettings.ts
src/routes/tsoa/login.ts
src/services/email/EmailOptions.ts
src/services/email/index.ts
src/services/email/mailchannels.ts
src/services/email/mailgun.ts
src/types/Client.ts
src/types/sql/Domain.ts
test/services/email/mailgun.spec.ts
test/services/getClient.spec.ts

Had some inconsistencies between the different client objects so we lost some settings..

fix: mailgun

---

src/routes/tsoa/users-mgmt.ts

:rocket: nice. this actually fixes the PUT endpoint
[Screencast from 2023-09-10 22-20-36.webm](https://github.com/sesamyab/auth/assets/8496063/6d4f0d33-87ec-425f-8b1f-ca92f2ca3977)

feat: update users-mgmt put endpoint

---

scripts/create-mjml-templates.sh
src/controllers/email.ts
src/email-templates/password-reset.mjml
src/hooks/update-client.ts
src/locales/en.ts
src/locales/sv.ts
src/templates/email/password-reset.liquid

Ok, this might not be prio.. But couldn't help to patch it up a bit :)

feat: patch up reset password

---

src/routes/tsoa/users-mgmt.ts

I wanted to do something generic but it turned out to be a bit tricky. Now it only supports filtering by email.

feat: support for auth0 user by email

---

src/controllers/email.ts
src/email-templates/code.mjml

Fetch the color for the magic link button from the client.

feat: set the color for the magic link button

---

src/email-templates/code.mjml
src/templates/email/code.liquid
test/routes/tsoa/passwordless.spec.ts

Move the button up in the body

fix: update magic link template

---

src/hooks/update-client.ts
test/services/getClient.spec.ts

We missed adding the support url to the client.

fix: add support url to client

---

src/email-templates/code.mjml
src/templates/email/code.liquid
test/routes/tsoa/passwordless.spec.ts

Let's release and Ferran can do a round #2
https://www.figma.com/file/5xnSBECWDO63KQDbDENdoq/Emails?type=design&node-id=496-282&mode=design&t=D1k7ocIcqFD8uwMH-0

feat: latest code email changes

---

src/adapters/planetscale/tenants/listTenants.ts

Adding these as I'm going along :+1:

fix: return count as number

---

src/utils/validate-redirect-url.ts

This was throwing before, but now it's skipping invalid urls

fix: skip invalid urls

---

integration-test/management-api/users.spec.ts
src/adapters/in-memory/user/index.ts
src/adapters/in-memory/user/listUsers.ts
src/adapters/interfaces/User.ts
src/adapters/planetscale/users/index.ts
src/adapters/planetscale/users/listUsers.ts
src/routes/management-api/users.ts
src/types/auth0/UserResponse.ts

In tandem with this PR https://github.com/sesamyab/auth-admin/pull/49
* I'm getting the integration tests working :heavy_check_mark: 
* I'm checking the PR diff and removing unneeded changes :heavy_check_mark: 
* I'll manually check the changes with React-admin :heavy_check_mark:  _working!_
Check comments
* filtering
* sorting
Probably worth writing integration tests for these

fix: clone newer tenants code to be used on users route

---

src/models/User.ts
src/routes/tsoa/dbconnection.ts

Added a static code for this user.

fix: add hardcoded user code

---

.github/workflows/deploy-dev.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml

Getting deprecation notices from GH!

feat: update GA actions

---

package.json
scripts/migrate.ts
src/migrate/migrations/2023-10-26T06:57:21_updated_at.ts
yarn.lock

Small typo in modified_at. Update the migration script so we can run it locally

fix: updated migrations and a script

---

src/routes/management-api/users.ts

Changed so getUser returns a UserRespone and only fetches the user from sql

fix: get user only from sql

---

src/migrate/migrations/2023-10-26T08:14:09_log_table.ts

feat: execute the v4 migration

---

package.json
src/app.ts
src/authentication.ts
src/routes/tsoa/connections.ts
wrangler.toml
yarn.lock

A few things that needed to be updated:
- Patched and pushed a new version of the tsoa-hono library to set response headers correctly
- CORS-config.. took a while to get this right
- Added the node-polyfill as we're using node buffers.. Think this isn't ideal, but it works

fix: headers and cors

---

src/app.ts

Can't use wildcard when allowing credentials.

fix: specific origin

---

src/app.ts
src/authentication-flows/silent.ts
src/routes/rotate-keys.ts
src/server.ts
src/services/datadog.ts
src/services/events.ts
src/types/Env.ts
src/types/Var.ts
test/models/User.spec.ts
wrangler.toml

Add the response headers and some an explicit log message. Cleaned up some rests of the queues since it was giving errors.

fix: log the token response

---

src/app.ts
src/utils/validate-redirect-url.ts

If the previous PRs are good then this will fix the CORS origin issue for our Vercel Preview deploys :crossed_fingers:

feat: add wilcard preview deploy origin and validate this

---

src/authentication-flows/social.ts
src/routes/tsoa/callback.ts

Add email and userId logs for callback

fix: callback logs

---

src/authentication.ts
src/utils/jwt.ts
src/utils/parse-jwt.ts
test/utils/jwt.spec.ts
wrangler.toml

Can't say I understand it completely but the tests passes :)

fix: header and encoding

---

src/models/User.ts
src/routes/tsoa/passwordless.ts

Add logging of code for debugging

fix: log code for debuggin

---

src/routes/management-api/users.ts
src/types/auth0/UserResponse.ts
src/types/sql/User.ts

This PR has a lot of comments in because I'm not sure! yay or nay them and I can remove the comments :+1:

feat: remove some non-existent mgmt api fields

---

src/adapters/in-memory/users/createUser.ts
src/adapters/in-memory/users/listUsers.ts
src/adapters/interfaces/Users.ts
src/authentication-flows/ticket.ts
src/helpers/generate-auth-response.ts
src/routes/tsoa/passwordless.ts
test/fixtures/context.ts
test/routes/tsoa/authorize.spec.ts
test/routes/tsoa/passwordless.spec.ts

My proposal for how to standardise this a bit :joy:  :facepalm: :upside_down_face: :racehorse:   *this one is probably a bit controversial* :smile: 
Part of the big chain of PRs :muscle:

fix: fix tests after merging previous PRs

---

src/migrate/migrations/2023-10-26T08:14:09_log_table.ts
src/migrate/migrations/2023-11-02T23:18:12_sessions.ts
src/migrate/migrations/2023-11-07T23:18:12_passwords.ts
src/migrate/migrations/2023-11-08T17:12:09_logs-table-new-fields.ts
src/migrate/migrations/index.ts

This PR
* reverts the logs table migration to how it was ran on production
* copies in the sessions and passwords migrations from the feature branch
* creates a new migration to add the new fields to the logs table :facepalm: 
*I THINK THAT IS ALL AND THIS WILL BE GOOD FOR PROD* :grimacing:

feat: fix all migrations

---

src/utils/validate-redirect-url.ts

Add apple url as it's used in the callback flow

fix: add apple callback

---

src/app.ts
src/utils/validate-redirect-url.ts

I guess this check shouldn't be throwing..

fix: add apple for cors

---

.github/workflows/unit-tests.yml
package.json
src/adapters/planetscale/users/createUser.ts
src/adapters/planetscale/users/get.ts
src/adapters/planetscale/users/getByEmail.ts
src/adapters/planetscale/users/list.ts
src/migrate/index.ts
src/routes/management-api/users.ts
src/routes/tsoa/applications.ts
src/routes/tsoa/dbconnection.ts
src/routes/tsoa/login.ts
src/routes/tsoa/userinfo.ts
yarn.lock

includes proper type checking :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes:

feat: update feature branchwith latest master

---

package.json
src/app.ts
src/authentication-flows/social.ts
src/errors.ts
src/migrate/migrations/2023-10-26T08:14:09_log_table.ts
src/migrate/migrations/2023-11-08T17:12:09_logs-table-new-fields.ts
src/migrate/migrations/index.ts
src/routes/tsoa/authorize.ts
src/routes/tsoa/logout.ts
src/routes/tsoa/passwordless.ts
src/utils/validate-redirect-url.ts
test/utils/validate-redirect-url.spec.ts

Probably worth having a quick check of what has changed to make sure we aren't losing anything :eye: :eye:

feat: another dan merge pr of main into the feature branch :cowboy_hat_face: 

---

src/routes/tsoa/login.ts
src/routes/tsoa/passwordless.ts

Now we've nuked most of the user model we need to fix the `tsoa/login` route!
*TBD* - lots of comments

fix: fix login route on feature branch

---

src/migrate/migrations/2023-11-21T15:57:00_user-indexes.ts
src/migrate/migrations/index.ts

Add an index for the user email as we query that quite a bit..

fix: add index on user email

---

.gitignore
src/routes/tsoa/login.ts
src/templates/render.ts

Will allow me to do sign-ups much more easily to fix the web component tests :partying_face:

fix: liquidjs login routes

---

src/migrate/migrations/2023-11-23T17:44:00_profile-data-field.ts
src/migrate/migrations/index.ts

Doing the migration as an initial PR always seems to cause less issues later :smile: 
(I still can't actually develop this though as SSO doesn't work on wrangler)

feat: new script to add profile data field

---

src/authentication-flows/social.ts
src/types/User.ts

I feel like there should be more steps than this *BUT* I figure we merge and I'll make more PRs to fix my mess :see_no_evil: 
Hopefully no one else is logging in on dev now with Social :smile:

feat: write id_token to new profile_data field

---

src/adapters/planetscale/users/list.ts

Add support for wildcard search.

fix: handle search without specified column

---

src/migrate/migrations/2023-11-23T17:44:00_profile-data-field.ts

Ooops. I should have done this on the previous PR!

fix: 2048 is largest before planet scale complains - done powers of 2

---

src/authentication-flows/social.ts

Works for Google & Facebook!
Apple: will do on another PR :upside_down_face:

fix: create social signon user if doesn't already exist

---

integration-test/management-api/tenants.spec.ts
integration-test/management-api/users.spec.ts
src/adapters/in-memory/tenants/list.ts
src/adapters/in-memory/users/list.ts
src/adapters/planetscale/tenants/listTenants.ts
src/routes/management-api/tenants.ts

In auth0 page 0 is the first page.

fix: paging

---

src/adapters/in-memory/logs/list.ts
src/adapters/interfaces/Logs.ts
src/adapters/planetscale/logs/list.ts
src/adapters/planetscale/tenants/listTenants.ts
src/adapters/planetscale/users/list.ts
src/routes/management-api/logs.ts
src/utils/getCountAsInt.ts

fix: Length property in logs endpoint is a string

---

integration-test/flows/silent-auth.spec.ts
integration-test/helpers/setup.ts
package.json
src/adapters/in-memory/applications/create.ts
src/adapters/interfaces/Applications.ts
src/adapters/planetscale/applications/create.ts
src/adapters/planetscale/applications/index.ts
src/adapters/planetscale/index.ts
src/routes/tsoa/applications.ts

I abandoned this before as I didn't need it and left it in a not so great state. This should fix it even though it's not 100% complete yet.

fix: application adapter

---

integration-test/management-api/users.spec.ts
src/routes/management-api/users.ts

I just guessed at the spec and API here :smile: 
Actually check what Auth0 does
I think I need to link and unlink some users, read the docs more, and understand our autolinking code...

feat: unlink account endpoint

---

wrangler.toml

Hopefully this will fix the release CI/CD :crossed_fingers:

feat: put back previous Wrangler DO migrations and add new one

---

wrangler.toml

I tried manually pushing this and it worked
I'll just merge this PR @markusahlstrand

fix: remove all references to DOs

---

integration-test/flows/code-flow.spec.ts
integration-test/flows/magic-link-flow.spec.ts
integration-test/flows/password.spec.ts
integration-test/flows/silent-auth.spec.ts
integration-test/flows/social.spec.ts
integration-test/jwks.spec.ts
integration-test/login/register-password-user.spec.ts
integration-test/management-api/tenants.spec.ts
integration-test/management-api/users.spec.ts
integration-test/ping.spec.ts
src/adapters/interfaces/Email.ts
src/types/Email.ts
tsconfig.json

I already did this on a few test suites
TypeScript FTW :smile:

test: type all unstable wrangler dev workers in integration tests

---

integration-test/management-api/tenants.spec.ts
src/adapters/in-memory/tenants/index.ts
src/adapters/in-memory/tenants/remove.ts
src/adapters/interfaces/Tenants.ts
src/adapters/kysely/tenants/index.ts
src/adapters/kysely/tenants/removeTenant.ts
src/routes/management-api/tenants.ts

Tested locally in auth-admin (as noted on ticket)

feat: delete tenant route

---

package.json
src/adapters/in-memory/Codes/create.ts
src/adapters/in-memory/applications/list.ts
src/adapters/in-memory/logs/list.ts
src/adapters/in-memory/members/list.ts
src/adapters/in-memory/tenants/list.ts
src/adapters/in-memory/users/list.ts
src/adapters/in-memory/utils/filter.ts
src/adapters/interfaces/Codes.ts
src/adapters/interfaces/Logs.ts
src/adapters/interfaces/Passwords.ts
src/adapters/kysely/applications/list.ts
src/adapters/kysely/logs/list.ts
src/adapters/kysely/members/list.ts
src/adapters/kysely/users/get.ts
src/adapters/kysely/users/getByEmail.ts
src/adapters/kysely/users/list.ts
src/authentication.ts
src/routes/tsoa/login.ts
src/templates/render.ts
test/fixtures/context.ts
test/fixtures/controller.ts
test/routes/tsoa/authenticate.spec.ts
test/utils/validate-redirect-url.spec.ts
tsconfig.json
yarn.lock

We're jumping out of typescript all the time here :smile: 
~*requires release of `tsoa-hono`*~  https://github.com/markusahlstrand/tsoa-hono/pull/3 :checkered_flag: Done and works

fix: no implicit anys!

---

migrate/migrate.ts
migrate/planetscale.ts
migrate/sqlite.ts
src/adapters/in-memory/clients/createClient.ts
src/adapters/interfaces/Clients.ts
src/adapters/kysely/clients/index.ts
src/adapters/kysely/index.ts
src/authentication-flows/social.ts
src/bun.ts
src/server.ts
src/services/clients.ts
test/fixtures/client.ts
test/fixtures/context.ts
test/routes/tsoa/token.spec.ts
test/services/getClient.spec.ts

Added the clients to the kysely adapter. Didn't yet remove any files but thought we can do that later in a separate PR if it all works out?
We should probably also add some caching here as it makes a couple of queries, but that's for later.

fix: fetch clients from sql on the fly

---

src/controllers/email.ts
src/email-templates/code.mjml
src/email-templates/link.mjml
src/locales/en.ts
src/locales/sv.ts
src/templates/email/code.liquid
src/templates/email/link.liquid

:warning: *when ready to merge, run script `scripts/create-mjml-templates.sh` to upload these to dev* :warning: 
:exclamation: _this PR only does the code and link emails_ :exclamation: 
I've been manually pushing them and testing on https://github.com/sesamyab/login2/pull/455 to confirm it works the same

feat: english code & link emails

---

migrate/migrations/2023-12-08T15:59:00_user-linked-to-index.ts
migrate/migrations/index.ts

Add a new index to speed things up.

fix: add index for user linked to

---

src/authentication-flows/social.ts
src/routes/tsoa/authorize.ts
src/routes/tsoa/passwordless.ts

Get the client with the fallbacks. Otherwise we just get the actual client.

fix: get client with fallbacks

---

migrate/planetscale.ts
migrate/sqlite.ts

Had sqlite in the planetscale script and vice versa..

fix: naming of migrate-scritps

---

README.md

I figure we should try and keep this up-to-date :smile: 
Comments welcome, maybe I've deleted too much. Happy to add also

fix: remove text from readme

---

integration-test/management-api/users-by-email.spec.ts
src/routes/management-api/users-by-email.ts
src/routes/management-api/users.ts
src/utils/enrichUser.ts

Lol!  I fixed existing bug on `main` on https://github.com/sesamyab/auth/pull/316
*when that is merged* rebase this PR onto `main` and should be all good :muscle:

feat: common helper function for selecting linked accounts

---

integration-test/flows/social.spec.ts
integration-test/mockOauth2Client.ts
package.json
src/authentication-flows/social.ts
src/routes/management-api/users.ts

@markusahlstrand I pointed a few PRs to `fix/wrong-user-object-used` but GitHub doesn't seem to work like it used to :smiling_face_with_tear: 
Maybe the branch also needs to be deleted to repoint to `main`. Either way. easy to fix, i'll just force merge this as the PRs going in are already approved

feat: merge everything in

---

integration-test/management-api/users-by-email.spec.ts
integration-test/test-server.ts

This will help tests on upcoming PRs

test: initial user test fixed should be username-password

---

integration-test/flows/code-flow.spec.ts
integration-test/flows/password.spec.ts
integration-test/flows/silent-auth.spec.ts
src/authentication-flows/ticket.ts
src/routes/tsoa/authorize.ts
test/authentication-flows/ticket.spec.ts
test/routes/tsoa/authorize.spec.ts

feat: autolink code user to same email on new signup

---

test/fixtures/client.ts
test/fixtures/context.ts

test: make fixtures screaming snake

---

integration-test/flows/code-flow.spec.ts
integration-test/flows/social.spec.ts
src/authentication-flows/ticket.ts
src/helpers/generate-auth-response.ts

Wow, this PR was meant to be adding more silent auth checks. I did, and I found a bug :see_no_evil:

fix: code signin was not returning primary account!

---

integration-test/flows/social.spec.ts

Nice. I expected our `/callback` to allow anything and create a user but makes sense! :sunglasses:

test: check malicious social provider cannot call us

---

integration-test/management-api/users-by-email.spec.ts
integration-test/management-api/users.spec.ts
src/routes/management-api/users.ts

This is what the profile is using

fix: add support for link with user_id

---

integration-test/management-api/users.spec.ts
package.json
src/routes/management-api/users.ts
yarn.lock

The email field was required before which failed the patches to fail

fix: patch user

---

src/adapters/kysely/users/booleans.ts
src/adapters/kysely/users/get.ts
src/adapters/kysely/users/list.ts

Mysql doesn't have support for booleans so it returns 0 or 1 instead for true or false

fix: handle booleans in users

---

integration-test/management-api/users.spec.ts
src/routes/management-api/users.ts

Seems like the user_id should contain the entire user id..

fix: linking

---

integration-test/flows/magic-link-flow.spec.ts

I thnk due to a copy-paste job, the magic link tests were just testing the code :police_officer:

test: magic link

---

integration-test/flows/magic-link-flow.spec.ts

We only had the happiest of happy-paths for the magic link

test: more magic link flow integration tests

---

integration-test/flows/code-flow.spec.ts

Nuking some of my comments and making the tests more comprehensive

test: more assertions on code flow

---

migrate/migrate.ts
test/integration/helpers/test-client.ts

fix: pass database into migration script

---

renovate.json

I'm taking the :+1: reaction from the boss as an approval of doing this :smile: 
Exciting times :robot: :robot: :robot: :robot:

feat: add renovate bot :sunglasses: 

---

integration-test/flows/social.spec.ts
integration-test/mockOauth2Client.ts
integration-test/test-server.ts

Not a huge amount of changes here!

fix: remove comments and do what they ask

---

integration-test/flows/password.spec.ts

This PR possibly begs more questions than it solves :clown_face:

test: more comprehensive username-password tests

---

integration-test/management-api/users-by-email.spec.ts
integration-test/management-api/users.spec.ts
src/routes/management-api/users.ts
test/integration/management-api/users.spec.ts

I recreated https://github.com/sesamyab/auth/pull/367

fix: account linking params should be inverted

---

migrate/migrations/2023-11-07T23:18:12_passwords.ts
test/integration/helpers/createTestUsers.ts
test/integration/helpers/test-client.ts
test/integration/management-api/users.spec.ts

I don't think this will be controversial... apart from maybe making each test take longer because we're adding more fixtures? :thinking: 
I'll do another PR as the remaining two fixtures cause everything to blow up

test: move the wrangler fixtures to hono tests

---

migrate/migrations/2023-11-02T23:18:12_sessions.ts

I spotted this while fixing the tenants table tests
This is needed first before the fix there

fix: correct table name for fk

---

migrate/migrations/2022-12-11T09:17:35_init.ts
migrate/migrations/2023-10-26T08:14:09_log_table.ts
migrate/migrations/2023-11-02T23:18:12_sessions.ts
migrate/migrations/2023-11-07T23:18:12_passwords.ts

I think this will trip us up in the tests at some point... if not actually on planetscale (which of course we aren't updating :sweat_smile: )

fix: add cascading delets to all fks

---

wrangler.toml

Maybe this is the undefined error we're getting from CI/CD wrangler deploys...

fix: revert routes to route

---

migrate/migrations/2024-01-06T16:23:00_logs-fields.ts
src/routes/management-api/users.ts
src/types/auth0/UserResponse.ts

The verify email should only determine if an email is sent or not.

fix: remove verify email property from user

---

src/routes/management-api/users.ts

Handle update so the same user.

fix: handle updates to the same user

---

src/helpers/silent-auth-cookie.ts
test/fixtures/client.ts
test/services/getClient.spec.ts

Feedback from https://github.com/sesamyab/auth/pull/403#event-11448207074

fix: empty keys in tests

---

.env.template
src/routes/tsoa/connections.ts

fix: connections patch

---

src/routes/management-api/tenants.ts
src/routes/management-api/users-by-email.ts
src/routes/management-api/users.ts
src/routes/tsoa/applications.ts
src/routes/tsoa/connections.ts
src/routes/tsoa/dbconnection.ts
src/routes/tsoa/domains.ts
src/routes/tsoa/members.ts
src/routes/tsoa/migrations.ts

I believe this is what you wanted!

feat: remove tsoa path args

---

src/authentication-flows/social.ts
src/services/oauth2-client.ts
src/types/Client.ts

I had a bit of naming confusion here. The client's thing is definitely making it harder.

fix: userinfo endpoint

---

migrate/migrations/2024-01-17T10:51:00_session-deleted-at.ts
migrate/migrations/index.ts
src/adapters/interfaces/Sessions.ts
src/adapters/kysely/sessions/create.ts
src/adapters/kysely/sessions/get.ts
src/adapters/kysely/sessions/index.ts
src/adapters/kysely/sessions/remove.ts
src/authentication-flows/silent.ts
src/routes/tsoa/authorize.ts
src/routes/tsoa/logout.ts
src/types/Session.ts
src/types/sql/Session.ts
test/integration/flows/logout.spec.ts
test/integration/helpers/silent-auth.ts
test/routes/tsoa/authorize.spec.ts

Logging out should invalidate the session. This way we could set a limit of how many sessions we can allow in parallel

fix: remove sessions when logging out

---

src/adapters/email/index.ts
src/bun.ts
src/helpers/generate-auth-response.ts
src/helpers/pkce.ts
src/routes/management-api/keys.ts
src/routes/swagger-ui.ts
src/server.ts
src/services/rsa-key.ts
src/token-grant-types/pkceAuthorizeCodeGrant.ts
test/fixtures/oauth2Client.ts
test/integration/helpers/test-client.ts
test/integration/mockOauth2Client.ts
test/routes/tsoa/passwordless.spec.ts
tsconfig.json

Following on from https://github.com/sesamyab/auth/pull/419 but with the typescript config `noUnusedParams`

chore: remove _even more_ code with TypeScript's `noUnusedParams`

---

package.json
yarn.lock

Major version upgrade! I figure this will blow up somehow :smile: 
Clearly not! If the tests pass then TSOA must be working right?

chore: upgrade tsoa to v6

---

src/controllers/email.ts
src/locales/en/default.json
src/locales/it/default.json
src/locales/no/default.json
src/locales/sv/default.json
src/utils/i18n.ts

* ~make sure these translations are all confirmed~ - I created an epic with all the tasks on! so this task is just to add it & no JSON
* ~add more screenshot tests to login2! Snapshot norwegiand and italian... (also should login and out there)~ Indeed. I'll do this as a future PR based on ticket https://app.shortcut.com/sesamy/story/5300/login2-extra-testing

feat: norwegian and italian i18n support

---

package.json
yarn.lock

The final test is merging this PR and letting it deploy :sunglasses:

chore: upgrade cloudflare packages

---

package.json
tsconfig.json
yarn.lock

chore: upgrade prettier

---

src/app.ts
src/routes/tsoa/login.ts
src/types/Code.ts

This fixes at least the first step of the password reset flow. Not sure if it will work all the way yet.

fix: password reset

---

src/locales/en/default.json
src/locales/it/default.json
src/locales/nb/default.json
src/locales/sv/default.json

chore: latest IT translations

---

migrate/migrations/2023-10-26T08:14:09_log_table.ts
src/app.ts
src/authentication-flows/silent.ts
src/authentication-flows/social.ts
src/routes/management-api/tenants.ts
src/routes/management-api/users-by-email.ts
src/routes/management-api/users.ts
src/routes/tsoa/passwordless.ts
src/tsoa-middlewares/logger.ts
src/types/Var.ts
test/integration/management-api/logs.spec.ts

I've cleared out the logs table on dev so we can start again

fix: set userid and tenantid on logs!

---

src/authentication-flows/silent.ts
src/authentication-flows/social.ts
src/authentication-flows/ticket.ts
src/routes/tsoa/authorize.ts
src/routes/tsoa/callback.ts
src/routes/tsoa/logout.ts
src/routes/tsoa/passwordless.ts
src/tsoa-middlewares/logger.ts

I think this is more in the right direction :crossed_fingers: 
Comments on PR so not ready to merge yet just FYI @markusahlstrand

feat: add logging to more routes

---

src/authentication-flows/social.ts
src/tsoa-middlewares/logger.ts

This PR is only small but I'd rather create many easy PRs :+1:

fix: set success sign up for social

---

src/routes/management-api/tenants.ts
src/routes/management-api/users.ts
src/routes/tsoa/authenticate.ts
src/routes/tsoa/authorize.ts
src/routes/tsoa/passwordless.ts
src/tsoa-middlewares/logger.ts

Ooops, I didn't realise https://auth0.com/docs/deploy-monitor/logs/log-event-type-codes existed
This is better than ChatGPT's suggestions :+1:

fix: match auth0 log event codes

---

src/services/token-factory.ts

As requested https://github.com/sesamyab/auth/pull/404#discussion_r1471327693

feat: use helper function to change null to undefined

---

src/adapters/kysely/logs/list.ts

:smile:   I'm fixing the logs page now

fix: logs page should start at 0

---

src/routes/management-api/users.ts

We are currently just returning `true/false` from the mgmt API patch endpoint
This isn't what auth0 does and react-admin isn't very happy either :smile:

fix: return patched user

---

src/routes/tsoa/authenticate.ts

Enriching the logs a bit more!

feat: log tenant id on authentication route

---

src/adapters/interfaces/Logs.ts
src/adapters/kysely/logs/get.ts
src/adapters/kysely/logs/index.ts
src/routes/management-api/logs.ts

Needed so I can do the log detail page on auth-admin :+1: 
Matches what Auth0 has

feat: logs get by id endpoint

---

src/adapters/kysely/users/get.ts
src/services/token-factory.ts
src/utils/enrichUser.ts

As discussed on previous PRs. De-duplicates the null>undefined mapping that we have in two places now

fix: map user null to undefined in data adapter

---

migrate/migrations/2024-02-02T15:55:00_drop-users-fields.ts
migrate/migrations/index.ts
scripts/upload-users.js

We're not using this at all anymore so better to :foot: :roll_of_paper:  :wastebasket:

feat: remove tags field on users

---

package.json
yarn.lock

Changelog only shows one line for this release...  :shrug:

chore: upgrade cookie package

---

src/types/Var.ts
src/types/auth0/LogsResponse.ts

Fairly uncontroversial!  I did a lot in one big PR and then the tests failed so I'm recreating it in manageable PRs

feat: extract out common auth0 type

---

src/authentication-flows/passwordless.ts
src/routes/tsoa/login.ts
src/utils/users.ts

Think this is more correct. In theory you could have multiple providers with the same connection type.

fix: check provider and not connection

---

src/authentication-flows/social.ts

Trying to do it in small steps like you like it :) This one is linked to the other PR. 
Think the linking part should be moved out as well as it will be the same in many flows.

fix: updated social login

---

migrate/migrations/2022-12-11T09:17:35_init.ts
migrate/migrations/2024-02-19T20:14:00_users-email-constrain.ts
migrate/migrations/index.ts
src/adapters/kysely/users/create.ts
test/integration/management-api/users.spec.ts

Added a constrain to ensure we don't create multiple users for with the same email for the same provider.

fix: added constrain for user and provider

---

src/app.ts

fix: obviously auth-admin is needed in allowed origins!

---

test/integration/flows/code-flow.spec.ts

Works! No code changes. Looks like it's just the mgmt api users endpoint that needs addressing...

test: case insensitive email address test on passwordless flow

---

src/authentication-flows/passwordless.ts
src/utils/users.ts
test/integration/flows/magic-link-flow.spec.ts

I figure I would recreate https://github.com/sesamyab/auth/pulls but just one flow at a time, as that PR has been sat there for months :clown_face: 
So this is just the magic link flow... Hopefully this makes sense and we can then apply this to the other routes one at a time

fix: magic link flow linked user

---

test/integration/flows/code-flow.spec.ts
test/integration/flows/magic-link-flow.spec.ts

This should all work without any new code as we're using the same `validateCode` util function

test: duplicate magic flow linked tests to code flow

---

test/integration/flows/code-flow.spec.ts
test/integration/flows/magic-link-flow.spec.ts
test/integration/helpers/test-client.ts
test/integration/management-api/logs.spec.ts

As requested in the previous PR!

test: remove /sv/ locale subpath from test fixtures

---

test/integration/management-api/users.spec.ts

Previous PR worked! No production code changes

test: lucene test with equals and searching for two things

---

src/adapters/kysely/users/update.ts

Oooops! my force merge done well

fix: remove undefined coercion oops

---

test/integration/management-api/users.spec.ts

As mentioned on another PR, helps us see the tests for each HTTP verb
Hide whitespace is key here! :smile:

test: wrap tests in more describe blocks

---

src/routes/tsoa/dbconnections.ts

Reverse engineer `auth0.js` using PRs on login2 e.g. https://github.com/sesamyab/login2/pull/580

feat: building dbconnections signup route

---

src/email-templates/password-reset.mjml
src/routes/tsoa/dbconnections.ts
src/routes/tsoa/login.ts
src/templates/email/password-reset.liquid
src/templates/universal/reset-password.ts

what is this called? it's called resetting the password but it's actually changing it...  Reset to me implies going back to 0... *anyway...*
_this does actually work!_ :partying_face: 
* I could write tests for all this *BUT*
* I think I should investigate email verification on Auth0 *and* come up with a solution. It's the last piece of the puzzle

feat: implement actual password changing

---

scripts/create-mjml-templates.sh
src/adapters/email/index.ts
src/adapters/interfaces/Email.ts
src/controllers/email.ts
src/email-templates/validate-email-address.mjml
src/routes/tsoa/dbconnections.ts
src/types/Code.ts
test/integration/helpers/test-client.ts

This doesn't actually validate the email, but I'm keeping the PRs bytesized :sunglasses: 
A lot is just copy-paste boilerplate

feat: email validation email

---

migrate/planetscale.ts

fix: planetscale migrate up

---

migrate/migrations/2024-03-11T12:45:00_increase-otp-state-length.ts
migrate/planetscale.ts
src/routes/management-api/users.ts

We always created the user with email, but still validated what the client passed. This should fix the create user from auth-admin..

fix: create user

---

src/types/Email.ts
test/integration/flows/password.spec.ts
test/integration/helpers/test-client.ts

One of my favourite PRs of all time I think :smiling_face_with_tear: 
Something for me to show the grandchildren

test: email validation flow

---

src/routes/tsoa/authenticate.ts
src/routes/tsoa/login.ts
test/integration/flows/password.spec.ts

This works *if* the existing user account with the same password *IS NOT* in itself linked :sunglasses: 
:black_joker: 
I think I know what my next task is :smile:

feat: link users post validation

---

test/integration/flows/password.spec.ts

Catching up on previous PRs where I wasn't testing anything

test: password reset flow

---

scripts/init-sqlite.ts
test/integration/flows/code-flow.spec.ts
test/integration/flows/logout.spec.ts
tsoa.mjs

Tried to get it running locally with bun and had to do a few small changes. Also found some unused code in the tests,

fix: changes for local dev

---

scripts/cleanup.ts
src/handlers/cleanup.ts

Added a cleanup script that removes old codes. We could schedule this to run once per night once we're happy with it.

fix: cleanup script

---

test/integration/management-api/users.spec.ts

I'm fairly certain that this bug was fixed by this PR https://github.com/sesamyab/auth/pull/547
I can revert this PR and test it if you want
Seems like we just need to release to fix the profile service issue!

test: show that get 409 when try and create duplicate linked code user

---

src/authentication-flows/passwordless.ts
src/authentication-flows/ticket.ts
src/routes/tsoa/dbconnections.ts
test/integration/flows/password.spec.ts

* resending email validation email on attempted login
* test this works
* refactor out util function from this change & `dbconnections/signup`

feat: send new verification email on attempted login

---

.gitignore
package.json
scripts/upload-css.sh
src/app.ts
src/styles/input.css
src/utils/components/Layout.tsx
src/utils/reactdemo.tsx
tailwind.config.js
tailwind.shared.config.js
yarn.lock

Tailwind proof-of-concept!
Kind of works :smile: 
1. I'll check this form actually works for changing the password
2. I could do some crude error outputting
3. Get Jonatan involved to start styling?

poc: can we use tailwind

---

src/utils/reactdemo.tsx

Wow. A bit of an excessively short PR but I didn't expect this to _just work_ :smile: 
I've QA'd it and I can indeed change the password. Works amazingly
* double password inputs? We're lacking this functionality on the login2 signup page... We should do that first
* error message! Do we need to do anything here? As clientside JS should tell the user if the password isn't matching all the rules :thinking:   _basically this is the first point again_

feat: form action works to change password!

---

src/app.ts
src/routes/tsx/routes.tsx
src/utils/reactdemo.tsx

Another PR where the diff is too large :see_no_evil:

fix: use JSX directly in routes

---

src/routes/tsx/routes.tsx
src/utils/components/Button.tsx
src/utils/components/ResetPasswordPage.tsx

this PR is small enough to not even need a description :see_no_evil:  Finally

feat: extract out components

---

src/routes/tsx/routes.tsx
src/utils/components/ResetPasswordPage.tsx
test/integration/flows/password.spec.ts

Adding @frankjonatanschultz for visibility of the technical debt nightmare that Markus and I have created :smile:

feat: double password entry

---

scripts/upload-css.sh
src/routes/tsx/routes.tsx
src/server.ts
src/types/Env.ts
src/types/sql/Tenant.ts
src/utils/components/AppLogo.tsx
src/utils/components/Layout.tsx
src/utils/components/ResetPasswordPage.tsx
tailwind.config.js
test/integration/helpers/test-client.ts

Check out the URL this ain't login2 :sunglasses:

feat: style forgot password form

---

src/styles/input.css
src/utils/components/Layout.tsx

One step closer!
Really not a million miles off scrapping login2 totally :sunglasses:

fix: set CSS variable colours from vendor settings styles

---

test/integration/flows/password.spec.ts

Ooops! I noticed this while doing other fixes

test: correctly testing weak password

---

src/routes/tsx/routes.tsx
src/utils/components/ResetPasswordPage.tsx

Comments welcome! I'm just adding any text for now :smile: 
I'll keep doing things until this looks like a login2 page

feat: show email address on reset password page

---

src/routes/tsx/routes.tsx
src/utils/components/AppLogo.tsx

Addressing Jonatan's comments from https://github.com/sesamyab/auth/pull/583/

fix: Jonatan PR comments

---

src/styles/fonts.css
src/styles/input.css
src/styles/uicon.css

Getting close to releasing this so no one can use it!
_previously_ the fonts weren't defined! see Chrome warning and the system fonts

feat: copy over fonts & uicon CSS from login2

---

src/controllers/email.ts
src/email-templates/password-reset.mjml
src/locales/en/default.json
src/locales/it/default.json
src/locales/nb/default.json
src/locales/sv/default.json
src/templates/email/code-v2.liquid
src/templates/email/link-v2.liquid
src/templates/email/password-reset.liquid
src/templates/email/verify-email.liquid

Same really as the verify email PR

feat: password reset email done enough

---

.github/workflows/unit-tests.yml

It's definitely quicker, by about 30 seconds or so

feat: try buildjet

---

src/controllers/email.ts
src/email-templates/password-reset.mjml
src/email-templates/verify-email.mjml
src/locales/en/default.json
src/locales/it/default.json
src/locales/nb/default.json
src/locales/sv/default.json
src/templates/email/code-v2.liquid
src/templates/email/link-v2.liquid
src/templates/email/password-reset.liquid
src/templates/email/verify-email.liquid

~Looks like this!  Let's merge this and I can check in Gmail~  I'm pushing to dev as I go along :smile: 
Comments welcome of course I just want to finish this :smile: 
-------------------------------------- 
Ok these are working now! it's all on dev already anyway

feat: new email templates

---

src/adapters/kysely/clients/index.ts
src/controllers/email.ts
src/types/Client.ts

Use the name of the tenant instead of the client

fix: use tenant name

---

src/routes/oauth2/well-known.ts

And.. now the return type validation works as well :)

fix: return types

---

src/app.ts
src/routes/management-api/users.ts
src/types/BaseEntity.ts
src/types/User.ts
src/types/auth0/Query.ts
src/types/auth0/Totals.ts
src/utils/sort.ts
test/integration/flows/code-flow.spec.ts
test/integration/flows/password.spec.ts
test/integration/flows/social.spec.ts
test/integration/helpers/createTestUsers.ts
test/integration/management-api/logs.spec.ts
test/integration/management-api/users-by-email.spec.ts
test/integration/management-api/users.spec.ts

Converted the users. Removed the logging for creating users for now and will add that in the next pr.

fix: convert users

---

src/adapters/interfaces/Users.ts
src/adapters/kysely/users/unlink.ts
src/routes/management-api/users.ts
test/integration/management-api/users.spec.ts

So, it seems that we didn't really do the unlinking according to the auth0 spec. I _think_ this should be right

fix: update unlink endpoint

---

src/routes/management-api/users.ts
src/tsoa-middlewares/logger.ts
test/integration/management-api/logs.spec.ts

Added the user log that was removed before

fix: user log

---

src/app.ts
src/routes/management-api/applications.ts
src/types/sql/Application.ts

This was smoother. Moved the applications over from the old openapi branch.

fix: migrate applications

---

src/routes/tsoa/callback.ts

Didn't we patch this before? Apple is passing back a user in some cases

fix: apple callback

---

src/app.ts
src/routes/management-api/logs.ts
src/routes/management-api/users.ts
src/tsoa-middlewares/logger.ts
src/types/auth0/LogsResponse.ts
src/utils/logs.ts
test/integration/management-api/logs.spec.ts

This was a bit painful.. All tests are passing but have a feeling we could improve this once the TSOA middlewares are gone.

fix: migrate logs

---

src/app.ts
src/routes/management-api/applications.ts

Moved to adapter and auth0 style

fix: move to api standard

---

src/routes/management-api/logs.ts
test/integration/management-api/logs.spec.ts

Same issue again.. had underscore instead of dash.. We need to add some tests..

fix: logs header

---

src/routes/management-api/users.ts

The logs function are depending on these properties being set.

fix: add userId and tenantId

---

src/adapters/interfaces/Connections.ts
src/adapters/kysely/connections/list.ts

Return auth0 response for listing connections

fix: list connections

---

src/routes/management-api/users.ts
src/utils/userIdParse.ts
test/fixtures/user.ts
test/helpers/generate-auth-tokens.spec.ts
test/integration/flows/code-flow.spec.ts
test/integration/flows/magic-link-flow.spec.ts
test/integration/flows/password.spec.ts
test/integration/helpers/test-client.ts
test/integration/management-api/users-by-email.spec.ts
test/integration/management-api/users.spec.ts
test/routes/tsoa/authenticate.spec.ts
test/routes/tsoa/authorize.spec.ts
test/routes/tsoa/passwordless.spec.ts
test/routes/tsoa/token.spec.ts

The console log warnings annoy me *but also* this actually matches what we're doing with real users :+1:

test: properly prefix test username

---

src/app.ts
src/bun.ts
src/middlewares/authentication.ts
test/helpers/generate-auth-tokens.spec.ts
test/integration/helpers/test-client.ts
test/integration/jwks.spec.ts

This adds a new auth middleware for the open-api routes. Also had to add a mocked jwks response for the tests to make it work.

fix: proper auth tokens for test

---

src/routes/tsoa/login.ts
src/routes/tsx/routes.tsx

I thought I'd start with an easy one and I'll branch them off each other :smile:

feat: login info route

---

src/routes/tsx/routes.tsx
src/utils/userIdParse.ts
test/fixtures/user.ts
test/helpers/generate-auth-tokens.spec.ts
test/integration/flows/code-flow.spec.ts
test/integration/flows/magic-link-flow.spec.ts
test/integration/flows/password.spec.ts
test/integration/helpers/test-client.ts
test/integration/management-api/users-by-email.spec.ts
test/integration/management-api/users.spec.ts
test/routes/tsoa/authenticate.spec.ts
test/routes/tsoa/authorize.spec.ts
test/routes/tsoa/passwordless.spec.ts
test/routes/tsoa/token.spec.ts

This will stop i18next from spamming the test console output :smile: 
It was also saying _You have already initialized i18next_ *but* it doesn't seem to matter (the tests still pass) and in production there's no server! :smile:

test: turn off i18n debug

---

src/routes/tsx/routes.tsx
src/templates/render.ts

@markusahlstrand this is the idea I mentioned elsewhere.

feat: extract out common from render methods

---

src/adapters/kysely/connections/create.ts
src/middlewares/authentication.ts
src/routes/management-api/connections.ts

Missed to add the id for the connections. Update the logic for the auth a bit as well to make it cleared.

fix: generate id in adapter

---

src/routes/management-api/connections.ts
src/services/clients.ts
src/services/oauth2-client.ts

This seems to fix the error we get in the auth-admin when we try to fetch a single connection.

fix: remove zod parse for connection

---

src/routes/tsoa/callback.ts
test/integration/flows/social.spec.ts

Apple posts with a form. In TSOA we accepted both but think this really is the standard..

fix: apple form post

---

migrate/migrations/2024-04-22T14:48:00_increase-ticket-state-length.ts
migrate/migrations/index.ts

fix: ticket state

---

test/integration/helpers/playwrightSnapshots.ts
test/integration/login/code-flow-liquidjs.spec.ts
test/integration/login/login-password.spec.ts
test/integration/login/register-password-user.spec.ts

Comments welcome. I think this makes sense. I'll do the same with the email snapshots next

test: snapshot response helper

---

src/routes/tsx/routes.tsx
test/integration/flows/password.spec.ts

Splitting out the reset-password changes from https://github.com/sesamyab/auth/pull/690

fix: reset password proper zod openapi

---

src/routes/tsx/routes.tsx
test/integration/flows/password.spec.ts

As mentioned https://github.com/sesamyab/auth/pull/692#issuecomment-2074509492
Was so nice to do this now all the types and routes are working :smile:

fix: reset password code in query string

---

src/routes/tsoa/callback.ts
test/integration/flows/password.spec.ts

Nothing major here is just oneline from a closed PR

test: actually use second (password reset) email in tests

---

src/routes/tsoa/login.ts
src/routes/tsx/routes.tsx
src/templates/render.ts
test/integration/login/forgot-password.spec.ts

Better to review and merge this one first https://github.com/sesamyab/auth/pull/699 as that snapshots the current forgot password form and route, so we'll know this PR hasn't broken anything

feat: migrate forgot password GET route to zod

---

src/routes/tsoa/passwordless.ts
test/integration/flows/magic-link-flow.spec.ts

This caused the login2 view to not render a valid email.

fix: double encoding

---

src/routes/oauth2/authenticate.ts
test/integration/login/code-flow.spec.ts

Not sure if we could handle this in the zod schema..

fix: empty code

---

package.json
src/adapters/interfaces/Domains.ts
src/adapters/interfaces/Logs.ts
src/app.ts
src/constants.ts
src/helpers/generate-auth-response-new.ts
src/routes/management-api/applications.ts
src/routes/management-api/domains.ts
src/routes/management-api/logs.ts
src/routes/management-api/users.ts
src/routes/tsx/routes.tsx
src/services/token-factory.ts
src/templates/render.ts
src/types/Token.ts
src/types/User.ts
src/types/auth0/LogsResponse.ts
src/types/auth0/UserResponse.ts
yarn.lock

I figure there'll be quite a few changes here so I'll do a few PRs
I can re-run the login2 tests... although I really hope passes here will catch everything
I'll change tsconfig to set `noUnusedLocals` and `noUnusedParameters` to true

feat: run knip round #1

---

scripts/init-sqlite.ts
src/adapters/kysely/logs/create.ts
src/adapters/kysely/otps/remove.ts
src/adapters/kysely/tickets/remove.ts
src/authentication-flows/silent.ts
src/helpers/apply-token-response.ts
src/helpers/generate-auth-response-new.ts
src/routes/management-api/applications.ts
src/routes/oauth2/logout.ts
src/routes/oauth2/well-known.ts
src/templates/render.ts
src/types/Client.ts
src/types/Token.ts
src/types/auth0/UserResponse.ts
test/integration/flows/code-flow.spec.ts
test/integration/flows/logout.spec.ts
test/integration/flows/magic-link-flow.spec.ts
test/integration/flows/password.spec.ts
test/integration/flows/silent-auth.spec.ts
test/integration/flows/social.spec.ts
test/integration/login/code-flow-liquidjs.spec.ts
test/integration/login/login-password.spec.ts
test/integration/login/register-password-user.spec.ts
test/integration/management-api/users-by-email.spec.ts
test/integration/management-api/users.spec.ts
test/utils/userIdParse.spec.ts
tsconfig.json

Done by setting `"noUnusedLocals": true,` in the tsconfig.

feat: removing unused vars

---

.github/workflows/unit-tests.yml
src/routes/management-api/logs.ts
test/integration/management-api/logs.spec.ts

The content-types were wrong so the typescript types weren't generated

fix: logs content types

---

src/routes/management-api/users.ts
test/integration/management-api/users.spec.ts

More fixes for the users endpoint. This fixes the users with totals.

fix: users with totals

---

src/routes/management-api/users-by-email.ts
src/routes/management-api/users.ts
src/utils/enrichUser.ts
test/integration/management-api/users-by-email.spec.ts

fix: more refactor of types

---

src/app.ts
src/services/datadog.ts
src/types/User.ts

We had the picture stored as an empty string in some cases which didn't pass validation. 
Also fixed the logger a bit so that it returns the validation error instead of crashing the process.

fix: remove url constrain

---

src/authentication-flows/universal.ts
test/integration/login/code-flow-liquidjs.spec.ts

This matches what we do on login2!

fix: redirect to enter code by default

---

src/routes/tsx/routes.tsx

As mentioned in another PR, it makes sense to extract out a helper function here

feat: first attempt at helper function

---

src/utils/components/SignUpPage.tsx

fix: signup email field

---

.github/workflows/unit-tests.yml
src/utils/components/LoginWithCodePage.tsx

Not tested but it looks like this should work

chore: upload any pngs from diffs

---

src/authentication-flows/social.ts
src/authentication-flows/ticket.ts
src/routes/oauth2/passwordless.ts

Use the authResponse method instead

chore: refactor silent auth response

---

test/integration/login/code-flow-liquidjs.spec.ts

This also works as we're using `validateCode` which handles the email user creation and account linking :thinking: 
Unexpected!  I'll keep creating PRs while migrating test-by-test... But this seems closer than I thought

test: universal auth code flow --- linking works

---

src/routes/oauth2/passwordless.ts
test/integration/flows/code-flow.spec.ts

Ooops! I found this one while writing tests for the universal auth code flow

fix: lowercase email on existing passwordless/start route

---

test/integration/login/code-flow-liquidjs.spec.ts

test: most complex linking flow

---

package.json
src/authentication-flows/social.ts
yarn.lock

Switch to use arctic for apple auth as a first step.

fix: use artic for apple auth

---

src/server.ts

feat: try-catch vendor settings error

---

src/server.ts
src/types/sql/Tenant.ts

feat: zod type for vendor settings and parse this

---

package.json
src/routes/tsx/routes.tsx
src/server.ts
src/types/Env.ts
src/types/sql/Tenant.ts
test/fixtures/vendorSettings.ts
test/integration/helpers/test-client.ts
vitest-setup.ts
vitest.config.ts
yarn.lock

Wow, I added mock service worker (as per the docs https://vitest.dev/guide/mocking.html#requests) and it worked first time :smile: 
Unexpected! But the tests pass (see previous test runs) so it must work :see_no_evil: 
We could actually have the tests run straight against the vendor settings endpoint but *lol* of course not

feat: do not mock vendor settings fetcher, mock the actual HTTP response

---

src/routes/oauth2/token.ts
src/token-grant-types/authorizationCodeGrant.ts

Use the default client in the auth grant flow

fix: auth grant default client

---

src/routes/tsx/routes.tsx
src/types/Env.ts
test/fixtures/context.ts
test/integration/helpers/test-client.ts
vitest-setup.ts
wrangler.toml

Also fallback to `client_id` if `vendor_id` not supplied

feat: use prod vendor settings endpoint

---

src/routes/tsx/routes.tsx
src/types/Env.ts
src/utils/components/LoginEnterCodePage.tsx
test/fixtures/context.ts
test/integration/helpers/test-client.ts
wrangler.toml

~Tests pass for me locally... Could be some github runner issue causing the tests to time out~ :+1:  Tests pass now

feat: whitelist which vendors should have password

---

src/styles/tailwind.ts
src/utils/components/Button.tsx
src/utils/components/Layout.tsx
src/utils/components/LoginEnterCodePage.tsx
src/utils/components/LoginWithCodePage.tsx
src/utils/components/Spinner.tsx

This duplicates the spinner functionality from the login2 button to here
~*BUT* we're not actually running React on the client :smile: , so I can add `isLoading` as a prop to the button~
Lol, not my greatest work, but this actually works :see_no_evil: 
[Screencast from 2024-05-23 10-54-25.webm](https://github.com/sesamyab/auth/assets/8496063/dc5d44e7-7ce3-44b1-93b8-ce9628cd5695)

feat: add spinner to code submission button

---

src/utils/components/LoginEnterCodePage.tsx

Seems to work
[Screencast from 2024-05-23 12-02-25.webm](https://github.com/sesamyab/auth/assets/8496063/7385b097-605a-46a5-8363-f60292e65d89)

feat: disabled spinner

---

src/utils/components/ForgotPasswordPage.tsx
src/utils/components/LoginPage.tsx
src/utils/components/LoginWithCodePage.tsx
src/utils/components/ResetPasswordPage.tsx
src/utils/components/SignUpPage.tsx

I noticed I hadn't set the titles

feat: add i18n titles

---

test/integration/login/login-password.spec.ts

This is testing what we currently have, not what we want :smile: 
I'll do more PRs branched off this where I add new functionality, and test it :saluting_face:

test: sign up tests

---

src/utils/components/DisabledSubmitButton.tsx
src/utils/components/ForgotPasswordPage.tsx
src/utils/components/Layout.tsx
src/utils/components/LoginEnterCodePage.tsx
src/utils/components/LoginPage.tsx
src/utils/components/LoginWithCodePage.tsx
src/utils/components/ResetPasswordPage.tsx
src/utils/components/SignUpPage.tsx

I think I'm adding too much untested functionality here :smile:

feat: disabled submit buttons on every form

---

src/routes/tsx/routes.tsx
test/integration/flows/password.spec.ts
test/integration/login/login-password.spec.ts

I'm migrating over tests and functionality from the existing auth0.js flows

feat: password login account linking (first round)

---

src/helpers/generate-auth-response.ts
src/routes/tsx/routes.tsx

Cherry picked the properties which might be what fixed it.

fix: code flow

---

test/integration/login/login-password.spec.ts

I must have merged an older branch into `main` that has an assertion that is no longer valid (as the page is now JSX)

test: remove assertion on new JSX page

---

package.json
src/utils/components/Button.tsx
src/utils/components/DisabledSubmitButton.tsx
src/utils/components/Layout.tsx
src/utils/components/SocialButton.tsx
test/integration/flows/code-flow.spec.ts
test/integration/flows/logout.spec.ts
test/integration/flows/password.spec.ts
test/integration/flows/silent-auth.spec.ts
test/integration/jwks.spec.ts
test/integration/userinfo.spec.ts
yarn.lock

We're a few minors out-of-date and we're looking at the latest docs a lot :smile:

feat: upgrade hono

---

test/integration/login/vendor-settings.spec.ts

Always annoys me seeing MSW and Zod outputting so much text on the vendor settings tests  :smile:

test: reduce test noise

---

test/integration/login/code-authorization.spec.ts
test/integration/login/login-password.spec.ts
test/integration/login/register-password-user.spec.ts

lol! I copy-pasted this code and was really confused that it still worked

test: fix bad assertion

---

test/integration/oauth/token.spec.ts

Tests have been merged in which weren't on the hono upgrade PR

fix: hono upgrade types

---

src/utils/base64.ts
src/utils/parse-jwt.ts
src/utils/stateEncode.ts
test/integration/breakit-customizations.spec.ts
test/integration/flows/social.spec.ts
test/utils/stateEncode.spec.ts

This is probably enough for a first round... ~I'll do another PR where I find&replace more native `btoa` calls with Oslo helpers~ I'm not sure if I should actually as those calls aren't base64 encoding URLs

test: use oslo instead of manual btoa

---

migrate/migrations/2024-06-05T10:00:00_otp-ip-address.ts

This fixes emails being sent on dev.  Migration already applied ~just an FYI!~ but we can of course revert and make any changes

fix: set varchar length

---

src/components/LoginPage.tsx
src/routes/tsx/routes.tsx
test/integration/login/cookie-selection.spec.ts

If this way isn't immediately clear I could create a new route to do this :see_no_evil:

fix: when hit code entry button we send a code email 

---

src/adapters/kysely/users/list.ts

Handle the case when there are no results

fix: handle empty users

---

src/routes/oauth2/passwordless.ts
test/integration/flows/code-flow.spec.ts

I'll manually test these as I do them
I could add tests though, but I figure currently nothing is working *and* we're going to be manually QAing these a lot

feat: log code/link sent on passwordless/start

---

src/routes/tsx/routes.tsx
test/integration/login/code-flow-liquidjs.spec.ts

Auth0 doesn't support codes on universal auth so I'm copying the logging style from the previous PR

feat: log cls for universal auth

---

test/integration/flows/code-flow.spec.ts

@markusahlstrand Fixing assertions after merging a few PRs to main :+1:   I'll force merge this

test: fix after merges

---

src/token-grant-types/authorizationCodeGrant.ts
src/types/auth0/LogsResponse.ts
test/integration/login/code-authorization.spec.ts

An additional log on Auth0's universal login after the token exchange

feat: logging success exchange authorization code for access token

---

src/adapters/kysely/users/create.ts
src/types/User.ts
test/integration/management-api/users.spec.ts

The database error is slightly different with planetscale compared to sqlite

fix: user conflict errors

---

src/routes/tsx/routes.tsx
test/integration/login/login-password.spec.ts

feat: log success login for universal auth password login

---

src/authentication-flows/passwordless.ts
src/authentication-flows/social.tsx
src/authentication-flows/ticket.ts
src/routes/tsx/routes.tsx

Now that the hook handles the merging of accounts we don't need this any longer. Think there were a few flows where the users weren't linked before :)

fix: remove linking

---

src/routes/tsx/routes.tsx
test/integration/login/register-password-user.spec.ts

One log, for one flow, with one test, at a time!

feat: success signup password universal auth

---

src/routes/tsx/routes.tsx
test/integration/login/login-password.spec.ts

matching more logging on Auth0!

feat: log failed password login

---

src/routes/oauth2/dbconnections.ts
test/integration/flows/password.spec.ts

One branch was merged into the other @markusahlstrand so I'll just merge this in as it was approved

fix: merge approved PR

---

src/authentication-flows/social.tsx
test/integration/flows/social.spec.ts

Matching more of the logs we get on Auth0

fix: success sso logs

---

src/routes/oauth2/callback.ts
test/integration/flows/social.spec.ts

This is already deployed to dev
This doesn't _fix_ the social flow starting from login2 because the button will take us back to the auth2 main screen...  but it's nice to know why

fix: init i18n on /callback

---

src/authentication-flows/silent.ts
test/integration/flows/password.spec.ts
test/integration/flows/silent-auth.spec.ts
test/integration/flows/social.spec.ts

Matching what Auth0 does. We aren't using this now we've moved off login2 *but* we might so may as well fix it for completeness

fix: log silent auth

---

src/authentication-flows/silent.ts
src/authentication-flows/ticket.ts
src/middlewares/authentication.ts
src/routes/management-api/users.ts
src/types/Var.ts

I'll leave this until all the other PRs are merged

fix: remove unread hono vars

---

src/routes/tsx/routes.tsx

Just moved things around a bit.

fix: minor refactor to simplify

---

migrate/migrations/2024-06-19T10:00:00_increase-user-agent-length.ts
migrate/migrations/index.ts
src/adapters/kysely/logs/create.ts

Script ran on dev: :heavy_check_mark:

fix: user agent sql length

---

test/integration/login/code-flow-liquidjs.spec.ts
test/integration/login/forgot-password.spec.ts
test/integration/login/login-password.spec.ts

I thought we had some weirdness with the email titles... I don't see this but no reason not to test this

test: assert subject on emails

---

src/app.ts
src/authentication-flows/password.ts
src/authentication-flows/silent.ts
src/authentication-flows/social.tsx
src/authentication-flows/ticket.ts
src/routes/management-api/users.ts
src/routes/oauth2/dbconnections.ts
src/routes/oauth2/logout.ts
src/routes/oauth2/passwordless.ts
src/routes/universal-login/routes.tsx
src/token-grant-types/authorizationCodeGrant.ts
src/utils/create-log-message.ts

Moved the util functions to create a log message and changed the order of the params.

chore: update signature

---

src/utils/create-log-message.ts

I can't see that auth0 logs these and it's pretty heavy.

fix: skip headers

---

src/authentication-flows/social.tsx
src/authentication-flows/ticket.ts
src/helpers/apply-token-response-new.ts
src/helpers/apply-token-response.ts
src/routes/oauth2/callback.ts
src/routes/oauth2/passwordless.ts
src/utils/magicLink.ts
src/utils/url.ts
test/integration/flows/password.spec.ts

We had a lot of repetitive code for setting search params.

fix: add helper for applying search params

---

src/authentication-flows/social.tsx
test/integration/flows/social.spec.ts

fix: add user id for social callback

---

src/authentication-flows/passwordless.ts
src/authentication-flows/ticket.ts
src/helpers/generate-auth-response.ts
test/integration/flows/code-flow.spec.ts
test/integration/flows/password.spec.ts

Various fixes for ticket login flow

fix: logs for ticket login

---

src/helpers/generate-auth-response.ts
src/routes/oauth2/token.ts
src/token-grant-types/authorizationCodeGrant.ts
src/types/auth0/LogsResponse.ts

Add the user-id to the code exchange flow. Add a flow for refresh token

fix: code exchange log

---

src/components/EmailValidatedPage.tsx
src/components/EnterCodePage.tsx
src/routes/universal-login/routes.tsx
src/types/Env.ts
test/integration/login/cookie-selection.spec.ts
test/integration/login/login-password.spec.ts

Update the references to the enter-password screen.

fix: update routes

---

src/authentication-flows/passwordless.ts
src/authentication-flows/social.tsx
src/authentication-flows/ticket.ts
src/authentication-flows/universal.ts
src/routes/oauth2/authenticate.ts
src/routes/oauth2/authorize.ts
src/routes/oauth2/callback.ts
src/routes/oauth2/dbconnections.ts
src/routes/oauth2/logout.ts
src/routes/oauth2/passwordless.ts
src/routes/universal-login/routes.tsx
src/services/clients.ts
src/token-grant-types/authorizationCodeGrant.ts
src/token-grant-types/clientCredentialsGrant.ts
src/token-grant-types/pkceAuthorizeCodeGrant.ts

Simplifies things if getClient throws if it isn't found.

fix: make get client throw if not found

---

src/adapters/interfaces/Hooks.ts
src/adapters/kysely/hooks/list.ts
src/routes/management-api/hooks.ts

Update the route endpoint so it follows the auth0 standard.

fix: route endpoint

---

src/adapters/interfaces/Connections.ts
src/adapters/interfaces/Hooks.ts
src/adapters/kysely/connections/get.ts
src/adapters/kysely/connections/index.ts
src/adapters/kysely/connections/remove.ts
src/adapters/kysely/connections/update.ts
src/adapters/kysely/hooks/get.ts
src/adapters/kysely/hooks/index.ts
src/adapters/kysely/hooks/remove.ts
src/routes/management-api/connections.ts
src/routes/management-api/hooks.ts

Also added missing adapter functions for connections so we're not using kysely directly

fix: add routes for get and delete

---

src/adapters/interfaces/Applications.ts
src/adapters/kysely/applications/get.ts
src/adapters/kysely/applications/index.ts
src/adapters/kysely/applications/remove.ts
src/adapters/kysely/applications/update.ts
src/routes/management-api/applications.ts
src/routes/management-api/hooks.ts
src/types/Application.ts
src/types/sql/db.ts

The routes were using kysely directly

fix: added missing functions

---

src/helpers/generate-auth-response.ts
src/hooks/index.ts
src/hooks/webhooks.ts
src/routes/management-api/hooks.ts

Added very simplistic invocation of web hooks

fix: invoke hooks

---

package.json
src/authentication-flows/silent.ts
src/helpers/generate-auth-response.ts
src/routes/oauth2/logout.ts
src/services/cookies.ts
yarn.lock

Switch to use oslo cookies as we already have that lib imported.

fix: use oslo cookies

---

src/routes/universal-login/routes.tsx
test/integration/login/cookie-selection.spec.ts

Only show the password option is there is a password user available

fix: check password user

---

migrate/migrations/2024-07-26T10:18:00_codes.ts
migrate/migrations/index.ts
package.json
scripts/init-sqlite.ts
src/authentication-flows/password.ts
src/authentication-flows/passwordless.ts
src/routes/management-api/domains.ts
src/routes/management-api/tenants.ts
src/routes/oauth2/dbconnections.ts
src/routes/universal-login/routes.tsx
src/utils/validate-redirect-url.ts
test/integration/helpers/test-server.ts
test/integration/login/forgot-password.spec.ts
test/integration/management-api/users.spec.ts
yarn.lock

Migrated the codes table as a first step to use a new logins table

fix: migrate codes tables

---

src/components/PreSignUpPage.tsx
src/routes/universal-login/routes.tsx
test/integration/flows/password.spec.ts
test/integration/login/login-password.spec.ts

We lost the code if you entered a invalid password

fix: signup flow

---

src/hooks/webhooks.ts
src/types/HookResponse.ts
src/types/index.ts

Add support for sync/async hooks

feat: hooks update

---

migrate/migrations/2024-08-16T13:45:00_saml.ts
package.json
src/models/DefaultSettings.ts
src/routes/management-api/applications.ts
src/services/clients.ts
test/integration/management-api/applications.spec.ts
yarn.lock

More refactor for the applications.

fix: workarounds for applications

---

src/authentication-flows/oauth2.tsx

Use the artic adapter to the the auth url

fix: use arctic for auth url

---

migrate/migrations/2023-12-26T10:58:00_signing-keys.ts
migrate/migrations/2024-08-26T18:38:00_cert.ts
migrate/migrations/index.ts
package.json
scripts/init-sqlite.ts
src/handlers/cleanup.ts
src/helpers/encryption.ts
src/helpers/generate-auth-response.ts
src/hooks/webhooks.ts
src/management-app.ts
src/routes/management-api/keys.ts
src/routes/oauth2/well-known.ts
src/routes/universal-login/routes.tsx
test/fixtures/context.ts
test/helpers/encryption.spec.ts
test/integration/helpers/test-server.ts
test/integration/helpers/token.ts
test/integration/mockOauth2Client.ts
yarn.lock

Use x509 certificates for signing keys

fix: temporarily comment out key type

---

src/authentication-flows/oauth2.tsx
src/types/Var.ts

Add a explicit error message and add a log message

fix: log callbacks without email

---

src/routes/management-api/applications.ts

More changes to get it work more like auth0

fix: update responses

---

src/helpers/generate-auth-response.ts
src/routes/universal-login/routes.tsx
test/integration/login/code-flow-liquidjs.spec.ts
test/integration/login/login-password.spec.ts

We were passing the univeral auth id as session id for code login

fix: silent auth when loggin in with code

---

src/components/Incognito.tsx
src/components/Layout.tsx
src/routes/universal-login/routes.tsx

This is a short term solution to test if a link to publishers page would work better.

fix: add a screen for incognito links
